apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- build-resources
- kueue

patches:
- target:
    kind: ClusterPolicy
    name: konflux-rbac-bootstrap-tenant-namespace-rbcm
  path: disable-konflux-rbac-bootstrap-on-roks.yaml
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: deny-unallowed-annotations
      namespace: tekton-kueue
