apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-infra-deployments/components/repository-validator/staging?ref=aaccbfc886b47595ed4168debf61f59c92b686f4
  - base-snapshot
