apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/konflux-ci/konflux-ci/operator/config/default?ref=be0e6cac273fe90ff6ef8e388a50c67be1308d52
  - konflux.yaml

images:
  - name: localhost/konflux-operator
    newName: quay.io/konflux-ci/konflux-operator
    newTag: be0e6cac273fe90ff6ef8e388a50c67be1308d52
