apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/konflux-ci/konflux-ci/operator/config/default?ref=41dc8341c5bfb5fbcf42d75840205484e7e4ff3b
  - konflux.yaml

images:
  - name: localhost/konflux-operator
    newName: quay.io/konflux-ci/konflux-operator
    newTag: 41dc8341c5bfb5fbcf42d75840205484e7e4ff3b
