apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: konflux-operator
  labels:
    appstudio.redhat.com/deployment-clusters: "tenant"
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: appstudio.redhat.com/select-none
                    operator: Exists
                  - key: appstudio.redhat.com/select-none
                    operator: DoesNotExist
              values:
                sourceRoot: components/konflux-operator
                ring: "empty-base"
                clusterDir: "empty-base"
          - list:
              elements: []
      selector:
        matchExpressions:
          - key: nameNormalized
            operator: In
            values:
              - kflux-lw-p01

  template:
    metadata:
      name: konflux-operator-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/rings/{{values.ring}}/{{values.clusterDir}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: konflux-operator
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
        retry:
          limit: -1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
