---
- op: add
  path: /spec/platforms/openshift/pipelinesAsCode/settings
  value:
    application-name: Konflux kflux-lw-p01
    custom-console-name: Konflux kflux-lw-p01
    custom-console-url: https://konflux-ui.kflux-lw-p01-23c2640bcea594f87bc757d4116925b2-0000.us-east.containers.appdomain.cloud
    custom-console-url-namespace: https://konflux-ui.kflux-lw-p01-23c2640bcea594f87bc757d4116925b2-0000.us-east.containers.appdomain.cloud/ns/{{ namespace }}
    custom-console-url-pr-details: https://konflux-ui.kflux-lw-p01-23c2640bcea594f87bc757d4116925b2-0000.us-east.containers.appdomain.cloud/ns/{{ namespace }}/pipelinerun/{{ pr }}
    custom-console-url-pr-tasklog: https://konflux-ui.kflux-lw-p01-23c2640bcea594f87bc757d4116925b2-0000.us-east.containers.appdomain.cloud/ns/{{ namespace }}/pipelinerun/{{ pr }}/logs/{{ task }}
    remember-ok-to-test: "false"
    secret-github-app-token-scoped: "false"
    enable-cancel-in-progress-on-pull-requests: "true"
