apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: konflux-operator
  labels: # Helps k-components detect this appset to apply the correct patches
    appstudio.redhat.com/deployment-clusters: "tenant"
    appstudio.redhat.com/internal-only: "true"
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              selector:
                  matchExpressions: # Ensures that no clusters are selected; k-components will replace this with the correct selector
                  - key: appstudio.redhat.com/select-none
                    operator: Exists
                  - key: appstudio.redhat.com/select-none
                    operator: DoesNotExist
              values:
                sourceRoot: components/konflux-operator
                ring: "empty-base"
                clusterDir: "empty-base"
          - list:
              elements: [] # Populated via k-components (or manually if the cluster list is unusual)

  template:
    metadata:
      name: konflux-operator-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/rings/{{values.ring}}/{{values.clusterDir}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: konflux-operator
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
        retry:
          limit: -1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
