apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-results
resources:
  - admin-crbs.yaml
  - info-rb.yaml
  - metrics-reader-crb.yaml
  - pipeline-service-sre-rb.yaml
  - read-only-cr.yaml
  - read-write-cr.yaml
  - testing-rbac.yaml
  - watcher-crb.yaml
  - watcher-rbac-crb.yaml
  - watcher-sa.yaml
