apiVersion: v1
kind: Pod
metadata:
  name: test-local-platform
spec:
  containers:
  - name: step-build
    resources:
      requests:
        cpu: "6"
        memory: 8Gi
      limits:
        cpu: "6"
        memory: 8Gi
