apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: unlabeled-broker-rolebinding
  namespace: unlabeled-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: konflux-art-token-broker-actions
subjects:
- kind: ServiceAccount
  name: art-token-broker
  namespace: art-token-broker
