apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- aws-account-es.yaml
- aws-ssh-key-es.yaml
- ibm-api-key-es.yaml
- ibm-s390x-ssh-key-es.yaml
- ibm-ppc64le-ssh-key-es.yaml
- ibm-s390x-static-ssh-key-es.yaml
