apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets-operator
resources:
- base-snapshot
helmGlobals:
  chartHome: base-snapshot
helmCharts:
- name: external-secrets
  releaseName: external-secrets-operator
  namespace: external-secrets-operator
  valuesFile: values.yaml
images:
- name: ghcr.io/external-secrets/external-secrets
  newName: quay.io/konflux-ci/external-secrets-operator
  newTag: cb0eb9773974a0aa47a0899ef9bcf8bde17bbabb
