apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: konflux-verifications-rd
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              values:
                sourceRoot: components/konflux-verifications-rd
                environment: staging
                clusterDir: "empty-base"
          - list:
              elements:
                - nameNormalized: stone-stage-p01
                  values.clusterDir: stone-stage-p01
  template:
    metadata:
      name: konflux-verifications-rd-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/{{values.environment}}/{{values.clusterDir}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: konflux-managed-tests
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: -1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
