apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-rbac-proxy
resources:
- ../base
- https://github.com/konflux-ci/image-rbac-proxy/deploy/development/base?ref=9b9f6effa9797ba66618ed97b6663db7207733cd
# Enable this to create/rotate oauth secret
- ../base/oauth

images:
- name: quay.io/konflux-ci/image-rbac-proxy
  newName: quay.io/konflux-ci/image-rbac-proxy
  newTag: 9b9f6effa9797ba66618ed97b6663db7207733cd
- name: memcached
  newName: quay.io/kubearchive/memcached
  newTag: 1.6.39
