apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-rbac-proxy
resources:
- ../base
- https://github.com/konflux-ci/image-rbac-proxy/deploy/development/base?ref=8fc718007abb984ee2f29acb860601f2bd1cdce6
# Enable this to create/rotate oauth secret
- ../base/oauth

images:
- name: quay.io/konflux-ci/image-rbac-proxy
  newName: quay.io/konflux-ci/image-rbac-proxy
  newTag: 8fc718007abb984ee2f29acb860601f2bd1cdce6
- name: memcached
  newName: quay.io/kubearchive/memcached
  newTag: 1.6.39
