apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-rbac-proxy
resources:
- ../base
- https://github.com/konflux-ci/image-rbac-proxy/deploy/development/base?ref=d3798d63c407463359dba1f64e2513a64e276dd0
# Enable this to create/rotate oauth secret
- ../base/oauth

images:
- name: quay.io/konflux-ci/image-rbac-proxy
  newName: quay.io/konflux-ci/image-rbac-proxy
  newTag: d3798d63c407463359dba1f64e2513a64e276dd0
- name: memcached
  newName: quay.io/kubearchive/memcached
  newTag: 1.6.39
