---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../base/external-secrets

namespace: konflux-kite

images:
  - name: quay.io/konflux-ci/kite-prod
    newTag: 80f43a9b27fa88843f43917cd8dcb30042004c88

  - name: quay.io/konflux-ci/kite-init
    newTag: 80f43a9b27fa88843f43917cd8dcb30042004c88
