---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../base/external-secrets
  - ../../base/cert-manager

namespace: konflux-kite

images:
  - name: quay.io/konflux-ci/kite-prod
    newTag: a2b99c1c998be3809ceab810849ac1860cc2bb45

  - name: quay.io/konflux-ci/kite-init
    newTag: a2b99c1c998be3809ceab810849ac1860cc2bb45
