apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: konflux-kite
  namespace: konflux-kite
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: konflux-kite
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 75
          type: Utilization
