apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secrets
  - rbac
  - namespace.yaml
  - tekton-chains-controller-svc-monitor.yaml
  - tekton-chains-service.yaml
