
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
    ignore-check.kube-linter.io/dangling-service: This service is not dangling, it
      exposes metric for an OSP deployment
  labels:
    app: tekton-chains-controller
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: tekton-chains
  name: tekton-chains
  namespace: openshift-pipelines
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-chains
