---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cos-credentials
  namespace: product-kubearchive-logging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-2"
spec:
  dataFrom:
    - extract:
        key: staging/platform/terraform/generated/lightwell-dev/cos-credentials
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: cos-credentials
    template:
      data:
        AWS_ACCESS_KEY_ID: '{{ .access_key_id }}'
        AWS_SECRET_ACCESS_KEY: '{{ .secret_access_key }}'
