apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: loki
name: loki
repo: https://grafana-community.github.io/helm-charts
version: 12.0.0
releaseName: loki
namespace: product-kubearchive-logging
valuesFile: loki-helm-values.yaml
additionalValuesFiles:
  - loki-helm-stg-values.yaml
  - loki-helm-images.yaml
valuesInline:
  serviceAccount:
    create: true
    name: loki-sa
  loki:
    storage:
      bucketNames:
        chunks: lightwell-dev-kubearchive-loki-6axo
        admin: lightwell-dev-kubearchive-loki-6axo
      s3:
        endpoint: s3.private.us-east.cloud-object-storage.appdomain.cloud
        s3ForcePathStyle: true
    storage_config:
      aws:
        bucketnames: lightwell-dev-kubearchive-loki-6axo
        endpoint: s3.private.us-east.cloud-object-storage.appdomain.cloud
        s3forcepathstyle: true
  ingester:
    extraEnvFrom:
      - secretRef:
          name: cos-credentials
  distributor:
    extraEnvFrom:
      - secretRef:
          name: cos-credentials
  querier:
    extraEnvFrom:
      - secretRef:
          name: cos-credentials
  compactor:
    extraEnvFrom:
      - secretRef:
          name: cos-credentials
  indexGateway:
    extraEnvFrom:
      - secretRef:
          name: cos-credentials
