apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base-snapshot
images:
- name: quay.io/konflux-ci/etcd-shield
  newTag: f0686af764673cde0a97466cf72f25fe871ce2a3
patches:
- target:
    kind: PrometheusRule
    name: etcd-shield-triggers
  path: prometheus-rule-severity-patch.yaml
