apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - runner
  - cluster-config-access.yaml
labels:
  - pairs:
      verification.konflux-ci.dev/team: konflux-vanguard
      verification.konflux-ci.dev/suite: proxy
    includeSelectors: false
    includeTemplates: false
