apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-token-manager
  namespace: verification-vanguard-proxy-runner
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    resourceNames: ["konflux-bot-0"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: konflux-vanguard-token-manager
  namespace: verification-vanguard-proxy-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sa-token-manager
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: konflux-vanguard
