apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-image-config
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              values:
                sourceRoot: configs/cluster-image-config
                environment: staging
                clusterDir: ""
          - list:
              elements:
                - nameNormalized: kflux-fedora-01
                  values.clusterDir: kflux-fedora-01
  template:
    metadata:
      name: cluster-image-config-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/{{values.environment}}/{{values.clusterDir}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: -1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
