apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- etcd-defrag-appset.yaml

patches:
  - path: exclude-roks-clusters.yaml
    target:
      kind: ApplicationSet
      group: argoproj.io
      version: v1alpha1
      name: etcd-defrag
