{
 "title": "KubeArchive Status",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Restarts in the last 24 hours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (increase(kube_pod_container_status_restarts_total{namespace=\"product-kubearchive\",pod=~\"kubearchive-operator-.*\"}[24h]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Number of tenants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_labels{label_konflux_ci_dev_type=\"tenant\", label_konflux_ci_type=\"user\"})",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "% usage of memory on the namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (namespace:container_memory_usage_bytes:sum{namespace=\"product-kubearchive\"}) / sum by (source_cluster) (namespace_memory:kube_pod_container_resource_limits:sum{namespace=\"product-kubearchive\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Konflux UP Metric",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "konflux_up{source_cluster=~\"$cluster\", service=~\"kubearchive-.*\"}",
     "legendFormat": "{{ source_cluster }} - {{ service }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memory_used{exported_job=~\"kubearchive.*\"}",
     "legendFormat": "{{ source_cluster }} - {{ exported_job }}"
    },
    {
     "expr": "go_memory_limit{exported_job=~\"kubearchive.*\"}",
     "legendFormat": "{{ source_cluster }} - {{ exported_job }} - limit"
    }
   ]
  },
  {
   "title": "Namespace Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(namespace_memory:kube_pod_container_resource_limits:sum{namespace=\"product-kubearchive\"}[4h])",
     "legendFormat": "Memory Limits"
    },
    {
     "expr": "avg_over_time(namespace_memory:kube_pod_container_resource_requests:sum{namespace=\"product-kubearchive\"}[4h])",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "namespace:container_memory_usage_bytes:sum{namespace=\"product-kubearchive\"}",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "avg_over_time(namespace_cpu:kube_pod_container_resource_limits:sum{namespace=\"product-kubearchive\"}[4h])",
     "legendFormat": "CPU Limits"
    },
    {
     "expr": "avg_over_time(namespace_cpu:kube_pod_container_resource_requests:sum{namespace=\"product-kubearchive\"}[4h])",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "namespace:container_cpu_usage:sum{namespace=\"product-kubearchive\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "All CloudEvents - 1 hour increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (queue) (increase(workqueue_adds{exported_job=\"kubearchive.operator\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Queued resource updates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(workqueue_depth{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (queue) (workqueue_depth{})",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Increase of retries during period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(workqueue_retries{}[$__range])",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Number of updates received in the period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(workqueue_adds{}[$__range]))",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "Number of accepted resources during period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_count{http_route=\"/\", exported_job=\"kubearchive.sink\"}[$__range]))",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "Average of ingestion latency during period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kubearchive:sink:latency{http_route!~\"(/livez|/readyz)\"} > 0)",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "Ingestion latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (http_status_code) (kubearchive:sink:latency{http_route!~\"(/livez|/readyz)\"} > 0)",
     "legendFormat": "{{ http_status_code }}"
    }
   ]
  },
  {
   "title": "Ingestion DB latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (method) (kubearchive:sink:db_latency{method!=\"sql.conn.ping\"} > 0)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  { "title": "Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Number of read responses during period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_count{http_route!~\"(/livez|/readyz)\", exported_job=\"kubearchive.api\"}[$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "% of 500 read responses during period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_count{http_route!~\"(/livez|/readyz)\", exported_job=\"kubearchive.api\", http_status_code=\"500\"}[$__range])) / sum(increase(http_server_request_duration_count{http_route!~\"(/livez|/readyz)\", exported_job=\"kubearchive.api\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average of read latency in the past 5 minutes (500)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kubearchive:api:latency{http_route!~\"(/livez|/readyz)\", http_status_code=\"500\"} > 0)",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "Number of 500 read responses during period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_count{http_route!~\"(/livez|/readyz)\", exported_job=\"kubearchive.api\", http_status_code=\"500\"}[$__range]))",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "Average of read latency in the past 5 minutes (non 500)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kubearchive:api:latency{http_route!~\"(/livez|/readyz)\", http_status_code!=\"500\"} > 0)",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "Read latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (http_status_code) (kubearchive:api:latency{http_route!~\"(/livez|/readyz)\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read DB latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (method) (kubearchive:api:db_latency{method!=\"sql.conn.ping\"} > 0)",
     "legendFormat": "{{ method }}"
    }
   ]
  }
 ]
}