resources:
  - ../base

patches:
  - target:
      kind: ExternalSecret
      name: ka-kubearchive-credentials
    patch: |
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: stonesoup/staging/monitoring/exporters/kaexporter/stone-stg-rh01
