apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

images:
- name: quay.io/konflux-ci/smee-sidecar
  newName: quay.io/konflux-ci/smee-sidecar
  newTag: adb6e692000c34cbce8a61112076d47003730b1c

patches:
  - path: sever-url-patch.yaml
    target:
      name: gosmee-client
      kind: Deployment
  - path: enable-pprof.yaml
    target:
      name: gosmee-client
      kind: Deployment
