apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

images:
- name: quay.io/konflux-ci/smee-sidecar
  newName: quay.io/konflux-ci/smee-sidecar
  newTag: 16f22690f7670b333a0f8f012fa5452b0c536f28

patches:
  - path: sever-url-patch.yaml
    target:
      name: gosmee-client
      kind: Deployment
  - path: enable-pprof.yaml
    target:
      name: gosmee-client
      kind: Deployment
