apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

images:
- name: quay.io/konflux-ci/smee-sidecar
  newName: quay.io/konflux-ci/smee-sidecar
  newTag: a8671721bcd89a8c681d7efd666b513321d873b3

patches:
  - path: sever-url-patch.yaml
    target:
      name: gosmee-client
      kind: Deployment
  - path: enable-pprof.yaml
    target:
      name: gosmee-client
      kind: Deployment
