apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-infra-deployments/components/repository-validator/staging?ref=37506bfa946531d47d4a9b5c6d0f4bb43aa56a39
  - base-snapshot
