apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- monitoringstack.yaml
- rbac.yaml
- servicemonitor.yaml
- servicemonitor-pipeline-exporter.yaml
- external-secrets/

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
