apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/development
  - https://github.com/konflux-ci/release-service/config/default?ref=d08813fc26b7557b01fff8527acb7c28b9722a83
  - release_service_config.yaml

images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/konflux-ci/release-service
    newTag: d08813fc26b7557b01fff8527acb7c28b9722a83

namespace: release-service

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: release-service-controller-manager
    path: manager-memory-patch.yaml
