apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/development
  - https://github.com/konflux-ci/release-service/config/default?ref=70b3c2e0b0d8553dedc753859e0b3f35ab58d842

images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/konflux-ci/release-service
    newTag: 70b3c2e0b0d8553dedc753859e0b3f35ab58d842

namespace: release-service
