apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/development
  - https://github.com/konflux-ci/release-service/config/default?ref=f9e179f3495a4f0b3cbac2b73c9969318d72351a
  - release_service_config.yaml

images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/konflux-ci/release-service
    newTag: f9e179f3495a4f0b3cbac2b73c9969318d72351a

namespace: release-service

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    path: sealights-token-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: release-service-controller-manager
    path: manager-memory-patch.yaml
