apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notification-controller

resources:
- https://github.com/konflux-ci/notification-service/config/default?ref=35aa4ee048a50919519a2e7af608ebf85fd1aa19
- aws-sns-es.yaml

images:
  - name: quay.io/konflux-ci/notification-service
    newName: quay.io/konflux-ci/notification-service
    newTag: 35aa4ee048a50919519a2e7af608ebf85fd1aa19

patches:
  - path: patches/topic_region_add-patch.yaml
    target:
      name: notification-controller-controller-manager
      kind: Deployment
  - path: patches/pipelinerun_filters-patch.yaml
    target:
      name: notification-controller-controller-manager
      kind: Deployment
