apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notification-controller

resources:
- https://github.com/konflux-ci/notification-service/config/default?ref=e10ea0e75259a450b375d33db062658f733ff79c
- aws-sns-es.yaml

images:
  - name: quay.io/konflux-ci/notification-service
    newName: quay.io/konflux-ci/notification-service
    newTag: e10ea0e75259a450b375d33db062658f733ff79c

patches:
  - path: patches/topic_region_add-patch.yaml
    target:
      name: notification-controller-controller-manager
      kind: Deployment
  - path: patches/pipelinerun_filters-patch.yaml
    target:
      name: notification-controller-controller-manager
      kind: Deployment
