apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notification-controller

resources:
- https://github.com/konflux-ci/notification-service/config/default?ref=ff23188d6cb5a41765530b87b826fb3147c64b2c
- aws-sns-es.yaml

images:
  - name: quay.io/konflux-ci/notification-service
    newName: quay.io/konflux-ci/notification-service
    newTag: ff23188d6cb5a41765530b87b826fb3147c64b2c

patches:
  - path: patches/topic_region_add-patch.yaml
    target:
      name: notification-controller-controller-manager
      kind: Deployment
  - path: patches/pipelinerun_filters-patch.yaml
    target:
      name: notification-controller-controller-manager
      kind: Deployment
