apiVersion: konflux.konflux-ci.dev/v1alpha1
kind: Konflux
metadata:
  name: konflux
spec:
  # Remaining non-team-owned sections for development.
  certManager:
    createClusterIssuer: true
  internalRegistry:
    enabled: true
  defaultTenant:
    enabled: true
