apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac
  - pipeline-metrics-exporter-deployment.yaml
  - pipeline-metrics-exporter-service.yaml
  - pipeline-service-svc-monitor.yaml
  - tekton-results-s3-es.yaml
