apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: konflux-kite-rd
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              selector:
                matchLabels:
                  appstudio.redhat.com/member-cluster: "true"
              values:
                sourceRoot: components/konflux-kite-rd
                ring: "ring-0"
                clusterDir: base
          - list:
              elements: []

  template:
    metadata:
      name: konflux-kite-{{nameNormalized}}
    spec:
      ignoreDifferences:
        - kind: ConfigMap
          group: ""
          name: kite-config-*
          jsonPointers:
            - /data
        - group: route.openshift.io
          kind: Route
          jsonPointers:
            - /spec/tls/destinationCACertificate
      project: default
      source:
        path: '{{values.sourceRoot}}/rings/{{values.ring}}/{{values.clusterDir}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: konflux-kite
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
        retry:
          limit: 50
          backoff:
            duration: 15s
