apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: mintmaker
patches:
  - path: pipelines-as-code-secret-path.yaml
    target:
      name: pipelines-as-code-secret
      group: external-secrets.io
      version: v1
      kind: ExternalSecret
  - path: ./patch_create-dependency-update-check_cron.yaml
    target:
      group: batch
      kind: CronJob
      name: create-dependencyupdatecheck
      namespace: mintmaker
      version: v1
  - path: manager_patch.yaml
