apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/mintmaker/config/default?ref=cb25fedc06eb646582c8f41268b338a9b0cbc9ca
  - https://github.com/konflux-ci/mintmaker/config/renovate?ref=cb25fedc06eb646582c8f41268b338a9b0cbc9ca

images:
  - name: quay.io/konflux-ci/mintmaker
    newName: quay.io/konflux-ci/mintmaker
    newTag: cb25fedc06eb646582c8f41268b338a9b0cbc9ca
  - name: quay.io/konflux-ci/mintmaker-renovate-image
    newName: quay.io/konflux-ci/mintmaker-renovate-image
    newTag: latest

namespace: mintmaker

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

configurations:
- kustomizeconfig.yaml

components:
  - ../components/rh-certs
