apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/mintmaker/config/default?ref=ed3bffaef417c38ca49d739a00e5ce77505c717e
  - https://github.com/konflux-ci/mintmaker/config/renovate?ref=ed3bffaef417c38ca49d739a00e5ce77505c717e

images:
  - name: quay.io/konflux-ci/mintmaker
    newName: quay.io/konflux-ci/mintmaker
    newTag: ed3bffaef417c38ca49d739a00e5ce77505c717e

namespace: mintmaker

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

components:
  - ../components/rh-certs
