apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/mintmaker/config/default?ref=9407f28c02f25ca9643a7b8fe66a59489e7e3dd6
  - https://github.com/konflux-ci/mintmaker/config/renovate?ref=9407f28c02f25ca9643a7b8fe66a59489e7e3dd6

images:
  - name: quay.io/konflux-ci/mintmaker
    newName: quay.io/konflux-ci/mintmaker
    newTag: 9407f28c02f25ca9643a7b8fe66a59489e7e3dd6
  - name: quay.io/konflux-ci/mintmaker-renovate-image
    newName: quay.io/konflux-ci/mintmaker-renovate-image
    newTag: latest

namespace: mintmaker

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

configurations:
- kustomizeconfig.yaml

components:
  - ../components/rh-certs
