apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    paas.redhat.com/appcode: MINT-001
resources:
- ../../base
- ../../base/external-secrets
- ../blackbox
- plrs-resource-quota.yaml
- https://github.com/konflux-ci/mintmaker/config/default?ref=7bc5ca7e6ecd17749926284e491173bc90b2222d
- https://github.com/konflux-ci/mintmaker/config/renovate?ref=7bc5ca7e6ecd17749926284e491173bc90b2222d

namespace: mintmaker

images:
- name: quay.io/konflux-ci/mintmaker
  newName: quay.io/konflux-ci/mintmaker
  newTag: 7bc5ca7e6ecd17749926284e491173bc90b2222d
- name: quay.io/konflux-ci/mintmaker-renovate-image
  newName: quay.io/konflux-ci/mintmaker-renovate-image
  newTag: 0410e2026b964953df7094e0455a2668305ad068

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

configMapGenerator:
  - name: controller-config
    files:
    - config.json

patches:
  - path: manager-mount-config-patch.yaml
  - path: manager-set-resources-patch.yaml
  - path: manager-enable-pprof-patch.yaml

configurations:
- kustomizeconfig.yaml

components:
  - ../../components/rh-certs
