images:
- path: spec/template/metadata/annotations/mintmaker.appstudio.redhat.com\/renovate-image
  kind: Deployment
- path: spec/template/metadata/annotations/mintmaker.konflux-ci.dev\/renovate-image
  kind: Deployment
