apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- ../blackbox
- https://github.com/konflux-ci/mintmaker/config/default?ref=9407f28c02f25ca9643a7b8fe66a59489e7e3dd6
- https://github.com/konflux-ci/mintmaker/config/renovate?ref=9407f28c02f25ca9643a7b8fe66a59489e7e3dd6

namespace: mintmaker

images:
- name: quay.io/konflux-ci/mintmaker
  newName: quay.io/konflux-ci/mintmaker
  newTag: 9407f28c02f25ca9643a7b8fe66a59489e7e3dd6
- name: quay.io/konflux-ci/mintmaker-renovate-image
  newName: quay.io/konflux-ci/mintmaker-renovate-image
  newTag: d07208a5aa6091aa2df38184c2940498c0a22fbd

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

configMapGenerator:
  - name: controller-config
    files:
    - config.json

patches:
  - path: manager-mount-config-patch.yaml
  - path: manager-set-resources-patch.yaml
  - path: manager-enable-pprof-patch.yaml

configurations:
- kustomizeconfig.yaml

components:
  - ../../components/rh-certs
