apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- ../blackbox
- https://github.com/konflux-ci/mintmaker/config/default?ref=5ce71bc86f592b13982ec09fb69d5ac43e9df6c5
- https://github.com/konflux-ci/mintmaker/config/renovate?ref=5ce71bc86f592b13982ec09fb69d5ac43e9df6c5

namespace: mintmaker

images:
- name: quay.io/konflux-ci/mintmaker
  newName: quay.io/konflux-ci/mintmaker
  newTag: 5ce71bc86f592b13982ec09fb69d5ac43e9df6c5
- name: quay.io/konflux-ci/mintmaker-renovate-image
  newName: quay.io/konflux-ci/mintmaker-renovate-image
  newTag: 85fe91716b6ac7c964c421ddf2c37c66c13aff1d

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

patches:
  - path: manager_patch.yaml

configurations:
- kustomizeconfig.yaml

components:
  - ../../components/rh-certs
