apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- component-maintainer-cr.yaml
- everyone-can-view-crs.yaml
- konflux-admins-cr.yaml
- konflux-admins-pod-admin-cr.yaml
- grafana-view-only-cr.yaml
- view-testplatformclusters-cr.yaml
- konflux-sre-cr.yaml

patches:
  - path: patches/everyone-can-view-patch.yaml
    target:
      name: everyone-view
      kind: ClusterRoleBinding
      group: rbac.authorization.k8s.io
      version: v1
  - path: patches/everyone-can-view-patch.yaml
    target:
      name: everyone-view-appstudio
      kind: ClusterRoleBinding
      group: rbac.authorization.k8s.io
      version: v1
  - path: patches/everyone-can-view-patch.yaml
    target:
      name: everyone-view-cluster-version
      kind: ClusterRoleBinding
      group: rbac.authorization.k8s.io
      version: v1
  - path: patches/everyone-can-view-patch.yaml
    target:
      name: everyone-view-cluster-monitoring
      kind: ClusterRoleBinding
      group: rbac.authorization.k8s.io
      version: v1
  - path: patches/everyone-can-view-patch.yaml
    target:
      name: everyone-view-compute
      kind: ClusterRoleBinding
      group: rbac.authorization.k8s.io
      version: v1
