apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/redhat-appstudio/o11y/config/exporters/monitoring/grafana/base?ref=1f8b27a4ab683a0cd7a82f9fa78b9f27e1d9e87a

images:
- name: quay.io/redhat-appstudio/o11y
  newName: quay.io/redhat-appstudio/o11y
  newTag: 1f8b27a4ab683a0cd7a82f9fa78b9f27e1d9e87a

patches:
  - path: auto-assign-role-patch.yaml
    target:
      name: grafana-oauth
      kind: Grafana
