apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/redhat-appstudio/o11y/config/exporters/monitoring/grafana/base?ref=edc9246d1200ec63453041bcf46559c30cc9a025

images:
- name: quay.io/redhat-appstudio/o11y
  newName: quay.io/redhat-appstudio/o11y
  newTag: edc9246d1200ec63453041bcf46559c30cc9a025

patches:
  - path: auto-assign-role-patch.yaml
    target:
      name: grafana-oauth
      kind: Grafana
