{
 "title": "Kepler Exporter Dashboard",
 "description": "Dashboard for Kepler Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_container_package_joules_total, container_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}, pod_name)"
    }
   },
   { "name": "watt_per_second_to_kWh", "query": "0.000000277777777777778" }
  ]
 },
 "panels": [
  { "title": "Power Consumption / Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node - CPU Architecture & Power Source",
   "type": "table",
   "description": "CPU architecture & Power source determined by Kepler",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count ( label_replace( kepler_node_info{container=\"kepler\"}, \"zz_components_power_source\", \"$1\", \"components_power_source\", \"(.+)\") ) by (cpu_architecture, zz_components_power_source, platform_power_source)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Energy Consumption (kWh) - Last 24 hours",
   "type": "stat",
   "description": "Total Energy Consumption (kWh) - Last 24 hours",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kepler:kepler:container_joules_total:consumed:24h:all * $watt_per_second_to_kWh"
    }
   ]
  },
  {
   "title": "Top 10 Energy Consuming Namespaces (kWh) in Last 24 hours",
   "type": "bargauge",
   "description": "Total Power Consumption for Top 10 Namespaces (kWh per day)",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, kepler:kepler:container_joules_total:consumed:24h:by_ns) * $watt_per_second_to_kWh",
     "legendFormat": "{{container_namespace}}"
    }
   ]
  },
  {
   "title": "Detailed Node Information",
   "type": "table",
   "description": "Architecture, Component and Power source per Instance",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "count (label_replace( kepler_node_info{container=\"kepler\"}, \"aa_instance\", \"$1\", \"instance\", \"(.+)\")) by (aa_instance, cpu_architecture, components_power_source, platform_power_source)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Power Consumption / Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total Power Consumption (W) in $namespace",
   "type": "timeseries",
   "description": "Total Power Consumption (W) in Namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(kepler:kepler:container_package_watts:1m:by_ns_pod{container_namespace=~\"$namespace\"})",
     "legendFormat": "PKG"
    },
    {
     "expr": "sum(kepler:kepler:container_dram_watts:1m:by_ns_pod{container_namespace=~\"$namespace\"})",
     "legendFormat": "DRAM"
    },
    {
     "expr": "sum(kepler:kepler:container_other_watts:1m:by_ns_pod{container_namespace=~\"$namespace\"})",
     "legendFormat": "OTHER"
    },
    {
     "expr": "sum(kepler:kepler:container_gpu_watts:1m:by_ns_pod{container_namespace=~\"$namespace\"})",
     "legendFormat": " GPU"
    }
   ]
  },
  {
   "title": "Total Energy Consumption in $namespace (kWh) - Last 1 hour",
   "type": "timeseries",
   "description": "Total Energy Consumption in Namespace (kWh) - Last 1 hour",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "kepler:kepler:container_package_joules_total:consumed:1h:by_ns{container_namespace=~\"$namespace\"} * $watt_per_second_to_kWh",
     "legendFormat": "PKG (CORE + UNCORE)"
    },
    {
     "expr": "kepler:kepler:container_dram_joules_total:consumed:1h:by_ns{container_namespace=~\"$namespace\"} * $watt_per_second_to_kWh",
     "legendFormat": "DRAM"
    },
    {
     "expr": "kepler:kepler:container_other_joules_total:consumed:1h:by_ns{container_namespace=~\"$namespace\"} * $watt_per_second_to_kWh",
     "legendFormat": "OTHER"
    },
    {
     "expr": "kepler:kepler:container_gpu_joules_total:consumed:1h:by_ns{container_namespace=~\"$namespace\"} * $watt_per_second_to_kWh",
     "legendFormat": " GPU"
    }
   ]
  },
  {
   "title": "PKG Power Consumption (W) by Pods in $namespace",
   "type": "timeseries",
   "description": "The total energy spent in PKG by a container.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "kepler:kepler:container_package_watts:1m:by_ns_pod{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "DRAM Power Consumption (W) by Pods in $namespace",
   "type": "timeseries",
   "description": "The total energy spent in DRAM by a container.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "kepler:kepler:container_dram_watts:1m:by_ns_pod{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "OTHER Power Consumption (W) by Pods in $namespace",
   "type": "timeseries",
   "description": "The total energy spent in OTHER by a container.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (pod_name) (kepler:kepler:container_other_watts:1m:by_ns_pod{container_namespace=~\"$namespace\", pod_name=~\"$pod\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "GPU Power Consumption (W) by Pods in $namespace",
   "type": "timeseries",
   "description": "The total energy spent in GPU by a container.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (pod_name) (kepler:kepler:container_gpu_watts:1m:by_ns_pod{container_namespace=~\"$namespace\", pod_name=~\"$pod\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}