apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/enterprise-contract/enterprise-contract-controller/config/crd?ref=05b2ae3928e41bf53104b944069bafc49fbc3f8d
  - ecp.yaml
  - role.yaml
  - rolebinding.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ec-defaults
    namespace: enterprise-contract-service
    literals:
      - verify_ec_task_bundle=quay.io/conforma/tekton-task:kf-38f45e69a0205377e5b1b040e53baa3a8fda0d74@sha256:82b8250d1a462ff176fe1eaa1f1d92dbc20b1c00e17b33c16e6c2ec17acdc23c
      - verify_ec_task_git_url=https://github.com/conforma/cli.git
      - verify_ec_task_git_revision=38f45e69a0205377e5b1b040e53baa3a8fda0d74
      - verify_ec_task_git_pathInRepo=tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml
      - verify_conforma_task_ta_git_pathInRepo=tasks/verify-conforma-konflux-ta/0.1/verify-conforma-konflux-ta.yaml
