apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/conforma/crds/config/crd?ref=9432cad0b14fc5eb3cc2b3cb2e71eac441a95ed9
  - ecp.yaml
  - role.yaml
  - rolebinding.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ec-defaults
    namespace: enterprise-contract-service
    literals:
      - verify_ec_task_bundle=quay.io/conforma/tekton-task:kf-e46c21e0fc9c74d14be2a47ba967a6acc4e6953e@sha256:6c589b0289fa034ba5ccb35ceefb7625d509b186c5cc5412f0045b53cf2c880a
      - verify_ec_task_git_url=https://github.com/conforma/cli.git
      - verify_ec_task_git_revision=e46c21e0fc9c74d14be2a47ba967a6acc4e6953e
      - verify_ec_task_git_pathInRepo=tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml
      - verify_conforma_task_ta_git_pathInRepo=tasks/verify-conforma-konflux-ta/0.1/verify-conforma-konflux-ta.yaml
