apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ibm-ppc64le-ssh-key-wkjg
  namespace: multi-platform-controller
  labels:
    build.appstudio.redhat.com/multi-platform-secret: "true"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  dataFrom:
    - extract:
        key: production/platform/terraform/generated/stone-prd-rh01/ibm-ppc64le-ssh-key-wkjg
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: ibm-ppc64le-ssh-key-wkjg
