apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - vmcluster.yaml
  - vmagent.yaml
  - platform-federation.yaml
  - tekton-scrapes.yaml
  - tekton-networkpolicy.yaml
  - scrape-networkpolicies.yaml
  - vmalert.yaml
  - vmrule.yaml
  - rbac.yaml
  - networkpolicy.yaml
generators:
  - operator-helm-generator.yaml
