apiVersion: v1
kind: ServiceAccount
metadata:
  name: vmagent-poc
  namespace: appstudio-vm-poc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmagent-poc-discovery
rules:
  - apiGroups: [""]
    resources: [nodes, pods, services, endpoints, namespaces]
    verbs: [get, list, watch]
  - apiGroups: [discovery.k8s.io]
    resources: [endpointslices]
    verbs: [get, list, watch]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [nodes/proxy, nodes/metrics]
    verbs: [get]
  - nonResourceURLs: [/metrics, /metrics/slis]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vmagent-poc-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmagent-poc-discovery
subjects:
  - kind: ServiceAccount
    name: vmagent-poc
    namespace: appstudio-vm-poc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vmagent-poc-platform-prometheus-api
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-monitoring-metrics-api
subjects:
  - kind: ServiceAccount
    name: vmagent-poc
    namespace: appstudio-vm-poc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vm-poc-maintainers
  namespace: appstudio-vm-poc
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: konflux-o11y
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: component-maintainer
