{
 "title": "KubeSaw - Proxy Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "95 quantile of list-workspace requests",
   "type": "timeseries",
   "description": "p95 latency of requests to list workspaces",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, status_code) (rate(sandbox_proxy_workspace_http_request_time_bucket{kube_verb=\"List\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time of list-workspace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate(sandbox_proxy_workspace_http_request_time_sum{kube_verb=\"List\"}[5m])) by (status_code)/sum(rate(sandbox_proxy_workspace_http_request_time_count{kube_verb=\"List\"}[5m])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95 quantile of get-workspace requests",
   "type": "timeseries",
   "description": "p95 latency of requests to get workspace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, status_code) (rate(sandbox_proxy_workspace_http_request_time_bucket{kube_verb=\"Get\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time of get-workspace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum (rate(sandbox_proxy_workspace_http_request_time_sum{kube_verb=\"Get\"}[5m])) by (status_code)/sum(rate(sandbox_proxy_workspace_http_request_time_count{kube_verb=\"Get\"}[5m])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95 quantile proxy api",
   "type": "timeseries",
   "description": "p95 latency of proxy api requests which is either accepted (202) or not accepted(406)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, status_code) (rate(sandbox_proxy_api_http_request_time_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time of Api Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum (rate(sandbox_proxy_api_http_request_time_sum[5m])) by (status_code) / sum(rate(sandbox_proxy_api_http_request_time_count[5m])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}