apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- limit-pod-serviceaccount-token-expiration-validationadmissionpolicy.yaml
- limit-pod-serviceaccount-token-expiration-validationadmissionpolicybinding.yaml
