apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-infra-deployments/components/repository-validator/production?ref=8b08c150b6ae2975f9f59149fc76d84aad007094
  - base-snapshot
