apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: pipeline-metrics-exporter
  name: pipeline-metrics-exporter-service
  namespace: openshift-pipelines
spec:
  ports:
  - name: metrics
    port: 9117
    protocol: TCP
    targetPort: 9117
  selector:
    app: pipeline-metrics-exporter
