apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- provider-config.yaml
- testplatform-provider-config.yaml
- https://github.com/konflux-ci/crossplane-control-plane/crossplane?ref=436006583e5203a6de0850569e76483aafbf6ea6
- https://github.com/konflux-ci/crossplane-control-plane/config?ref=436006583e5203a6de0850569e76483aafbf6ea6

images:
  - name: quay.io/konflux-ci/appstudio-utils
    newName: quay.io/konflux-ci/task-runner
    newTag: v1
    digest: sha256:b9ef0479b57a494368a12a02886c650314c9ac7391c6228f21065865aab71c9e

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 4Gi
    target:
      kind: Deployment
      name: crossplane-helm
      namespace: crossplane-system
