apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apply-tekton-cfg-crb.yaml
  - jobs-admin-crb.yaml
  - pipeline-exporter-crb.yaml
  - pipeline-service-sre-rb.yaml
  - resolution-req-perms-exporter-crb.yaml
  - tekton-chains-public-key-crbs.yaml
