{
 "title": "Kueue",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Kueue Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Admission Attempt Latency",
   "type": "heatmap",
   "description": "The latency of an admission attempt.",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (rate(kueue_admission_attempt_duration_seconds_bucket[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  kube_deployment_status_replicas_available{namespace=~\"openshift-kueue-operator|tekton-kueue|kueue-external-admission\"}\n)\n/\nclamp_min(\n  kube_deployment_spec_replicas{namespace=~\"openshift-kueue-operator|tekton-kueue|kueue-external-admission\"},\n  1\n) * 100",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  { "title": "Cluster Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Queue Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by (status) (kueue_cluster_queue_status{cluster_queue=\"cluster-pipeline-queue\"}) == 1",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Pending Workloads",
   "type": "stat",
   "description": "The number of pending workloads",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (status) (kueue_pending_workloads{cluster_queue=\"cluster-pipeline-queue\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Admitted Active Workloads",
   "type": "stat",
   "description": "The number of admitted Workloads that are active (unsuspended and not finished)",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kueue_admitted_active_workloads{cluster_queue=\"cluster-pipeline-queue\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Reservation / Nominal Quota",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (resource) (kueue_cluster_queue_resource_reservation{cluster_queue=\"cluster-pipeline-queue\"} /kueue_cluster_queue_nominal_quota{cluster_queue=\"cluster-pipeline-queue\"} * 100)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Resource Usage / Reservation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (resource) (kueue_cluster_queue_resource_usage{cluster_queue=\"cluster-pipeline-queue\"} / kueue_cluster_queue_resource_reservation{cluster_queue=\"cluster-pipeline-queue\"} * 100)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Admission Wait Time",
   "type": "heatmap",
   "description": "kueue_admission_wait_time_seconds",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by (le) (rate(kueue_admission_wait_time_seconds_bucket{cluster_queue=\"cluster-pipeline-queue\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quota Reserved Wait Time",
   "type": "heatmap",
   "description": "The time between a workload was created or requeued until it got quota reservation",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by (le) (rate(kueue_quota_reserved_wait_time_seconds_bucket{cluster_queue=\"cluster-pipeline-queue\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Admission Check Wait Time",
   "type": "heatmap",
   "description": "The time from when a workload got the quota reservation until admission",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum by (le) (rate(kueue_admission_checks_wait_time_seconds_bucket{cluster_queue=\"cluster-pipeline-queue\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Tenants",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 93 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_namespace_labels{label_konflux_ci_dev_type=\"tenant\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Workloads vs Etcd Usage",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 13, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "max(kueue_admitted_active_workloads{cluster_queue=\"cluster-pipeline-queue\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(etcd_mvcc_db_total_size_in_use_in_bytes)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}