apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder:e12db27675d844076ee9f445b8767de7711a9127
      additional-params:
      - build-platforms
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build:e12db27675d844076ee9f445b8767de7711a9127
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta:e12db27675d844076ee9f445b8767de7711a9127
    - name: docker-build-multi-platform-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-multi-platform-oci-ta:e12db27675d844076ee9f445b8767de7711a9127
      additional-params:
      - build-platforms
    - name: maven-zip-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-maven-zip-build:e12db27675d844076ee9f445b8767de7711a9127
    - name: maven-zip-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-maven-zip-build-oci-ta:e12db27675d844076ee9f445b8767de7711a9127
    - name: tekton-bundle-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder:e12db27675d844076ee9f445b8767de7711a9127
