apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder:dd74c97a6752d42df3e1146c86961cca24f8a099
      additional-params:
      - build-platforms
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build:dd74c97a6752d42df3e1146c86961cca24f8a099
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta:dd74c97a6752d42df3e1146c86961cca24f8a099
    - name: docker-build-multi-platform-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-multi-platform-oci-ta:dd74c97a6752d42df3e1146c86961cca24f8a099
      additional-params:
      - build-platforms
    - name: maven-zip-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-maven-zip-build:dd74c97a6752d42df3e1146c86961cca24f8a099
    - name: maven-zip-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-maven-zip-build-oci-ta:dd74c97a6752d42df3e1146c86961cca24f8a099
    - name: tekton-bundle-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder:dd74c97a6752d42df3e1146c86961cca24f8a099
