apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/infra-deployments//components/dummy-deployment/base?ref=649e59ab6d215e4a6d27d9c0895f08e0e5efdf20
- https://github.com/flacatus/konflux-dummy-deploy//k8s?ref=af9b4550185300620210cf086dace680c81dc97c

images:
- name: quay.io/redhat-appstudio-qe/dummy-deployment
  newTag: af9b4550185300620210cf086dace680c81dc97c

patches:
- target:
    kind: ConfigMap
    name: dummy-deployment-config
  patch: |
    - op: replace
      path: /data/DISPLAY_TEXT
      value: "Hello from STAGE!"
