
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: appstudio-grafana
spec:
  config:
    resources:
      limits:
        cpu: "800m"
        memory: "1Gi"
      requests:
        cpu: "400m"
        memory: "512Mi"
    env:
      - name: ENABLE_LEADER_ELECTION    # Staging: Disable leader election and tune operator via Subscription env vars
        value: "false"
