apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/redhat-appstudio/o11y/config/exporters/monitoring/grafana/base?ref=48d18437d8de5e791574d69272bb9def79cb921c

images:
- name: quay.io/redhat-appstudio/o11y
  newName: quay.io/redhat-appstudio/o11y
  newTag: 48d18437d8de5e791574d69272bb9def79cb921c

patches:
  - path: grafana-resources-patch.yaml
    target:
      name: grafana-oauth
      kind: Grafana
  - path: auto-assign-role-patch.yaml
    target:
      name: grafana-oauth
      kind: Grafana
