apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base-snapshot
- https://github.com/konflux-ci/project-controller/config/default?ref=37eff6ae568bd54b0f8d1bfb7912d048f39544cb
images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: 37eff6ae568bd54b0f8d1bfb7912d048f39544cb
namespace: project-controller
