---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: conformance-test-runner-admin
  namespace: konflux-conformance-tests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: konflux-admin-user-actions
subjects:
- kind: ServiceAccount
  name: conformance-test-runner
  namespace: konflux-managed-tests
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: conformance-test-runner-extra
  namespace: konflux-managed-tests
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: conformance-test-runner-extra
  namespace: konflux-managed-tests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: conformance-test-runner-extra
subjects:
- kind: ServiceAccount
  name: conformance-test-runner
  namespace: konflux-managed-tests
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: conformance-test-runner-admin
  namespace: konflux-managed-tests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: konflux-admin-user-actions
subjects:
- kind: ServiceAccount
  name: conformance-test-runner
  namespace: konflux-managed-tests
