{
 "title": "Migration Team",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "Pipelines Count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (increase(tekton_pipelines_controller_pipelinerun_duration_seconds_count{namespace!~\"tekton-ci|build-templates-e2e\"}[$__range]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Pipelines Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace)\n(increase(tekton_pipelines_controller_pipelinerun_duration_seconds_count{namespace!~\"tekton-ci|build-templates-e2e\", status=\"success\"}[$__range])) \n/\nsum by (namespace)\n(increase(tekton_pipelines_controller_pipelinerun_duration_seconds_count{namespace!~\"tekton-ci|build-templates-e2e\"}[$__range])) * 100",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Taskrun Pod Latency",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (namespace) (tekton_pipelines_controller_taskruns_pod_latency) / 10^9",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}