apiVersion: v1
data:
  alert-content.json: |
    {
      "summary": "There is an example system alert!",
      "type": "Info"
    }
kind: ConfigMap
metadata:
  labels:
    konflux-auto-alert: "true"
  name: konflux-autoalert-configmap-1
  namespace: konflux-info
