apiVersion: konflux.konflux-ci.dev/v1alpha1
kind: Konflux
metadata:
  name: konflux
spec:
  ui:
    spec:
      ingress:
        hostname: konflux-ui
      runtimeConfig:
        chatBot:
          enabled: false
        monitoring:
          cluster: stone-stage-p01
