apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multi-platform-controller
resources:
- base-snapshot
- https://github.com/konflux-ci/multi-platform-controller/deploy/operator?ref=3f45c507b695b7cc228aded5d4ce5d43060c6af4
- https://github.com/konflux-ci/multi-platform-controller/deploy/otp?ref=3f45c507b695b7cc228aded5d4ce5d43060c6af4
images:
- name: multi-platform-controller
  newName: quay.io/konflux-ci/multi-platform-controller
  newTag: 3f45c507b695b7cc228aded5d4ce5d43060c6af4
- name: multi-platform-otp-server
  newName: quay.io/konflux-ci/multi-platform-controller-otp-service
  newTag: 3f45c507b695b7cc228aded5d4ce5d43060c6af4
patches:
- path: patches/manager-resources-patch.yaml
