apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multi-platform-controller
resources:
- base-snapshot
- https://github.com/konflux-ci/multi-platform-controller/deploy/operator?ref=968e2ea8b0ec4eab076095dc963a63faa19b2f40
- https://github.com/konflux-ci/multi-platform-controller/deploy/otp?ref=968e2ea8b0ec4eab076095dc963a63faa19b2f40
- host-config-cm.yaml
images:
- name: multi-platform-controller
  newName: quay.io/konflux-ci/multi-platform-controller
  newTag: 968e2ea8b0ec4eab076095dc963a63faa19b2f40
- name: multi-platform-otp-server
  newName: quay.io/konflux-ci/multi-platform-controller-otp-service
  newTag: 968e2ea8b0ec4eab076095dc963a63faa19b2f40
patches:
- path: patches/logs-in-console-format-cmd-arg-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: multi-platform-controller
