apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipelines-controller-konflux-scc
  annotations:
    argocd.argoproj.io/sync-wave: 0
roleRef:
  name: appstudio-pipelines-runner
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
- name: tekton-pipelines-controller
  kind: ServiceAccount
  namespace: openshift-pipelines
