apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kube-shard-appset.yaml

patches:
  - path: include-lightwell-dev.yaml
    target:
      kind: ApplicationSet
      version: v1alpha1
      name: kube-shard
