apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: etcd-shield:cluster-monitoring-view
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: etcd-shield
  namespace: etcd-shield
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
