apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/konflux-ci/notification-service/config/default?ref=e824a54381b98f7ebd0320348cfe1b2debef0e3a
- ../base/external-secrets

images:
  - name: quay.io/konflux-ci/notification-service
    newName: quay.io/konflux-ci/notification-service
    newTag: e824a54381b98f7ebd0320348cfe1b2debef0e3a

namespace: notification-controller

patches:
  - path: external-secret-path.yaml
    target:
      name: aws-sns-secret
      kind: ExternalSecret
      group: external-secrets.io
      version: v1
  - path: topic_region_add.yaml
    target:
      name: notification-controller-controller-manager
      kind: Deployment
