---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.konflux-ci.dev/aggregate-to-admin: "true"
  name: konflux-admin-workloads.kueue.x-k8s.io
rules:
  - apiGroups:
      - kueue.x-k8s.io
    resources:
      - workloads
    verbs:
      - get
      - list
      - watch
