apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base-snapshot
- https://github.com/konflux-ci/project-controller/config/default?ref=86d07465d3298572fd55dff70a644436a124a09a
images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: 86d07465d3298572fd55dff70a644436a124a09a
namespace: project-controller
