resources:
  - ../base

patches:
  - target:
      kind: ExternalSecret
      name: ka-kubearchive-credentials
    patch: |
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: stonesoup/production/monitoring/exporters/kaexporter/kflux-fedora-01
