apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deny-art-token-broker-clusterrolebindings-validatingadmissionpolicy.yaml
- deny-art-token-broker-clusterrolebindings-validatingadmissionpolicybinding.yaml
- restrict-art-token-broker-bindings-validatingadmissionpolicy.yaml
- restrict-art-token-broker-bindings-validatingadmissionpolicybinding.yaml
