apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- https://github.com/konflux-ci/project-controller/config/default?ref=12895fbb7ca950146bb6f840bf5bb235884cc185

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: 12895fbb7ca950146bb6f840bf5bb235884cc185

namespace: project-controller
