apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- https://github.com/konflux-ci/project-controller/config/default?ref=8a174ecd262797e856968876e7b2f0d84377dfa7

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: 8a174ecd262797e856968876e7b2f0d84377dfa7

namespace: project-controller
