apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- https://github.com/konflux-ci/project-controller/config/default?ref=d2241aa2d746e2f96275bfafac17d6d2e3e9f792

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: d2241aa2d746e2f96275bfafac17d6d2e3e9f792

namespace: project-controller
