{
 "title": "Kueue",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Kueue Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Admission Attempt Latency",
   "type": "heatmap",
   "description": "The latency of an admission attempt.",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (increase(kueue_admission_attempt_duration_seconds_bucket[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  kube_deployment_status_replicas_available{namespace=~\"openshift-kueue-operator|tekton-kueue\"}\n)\n/\nclamp_min(\n  kube_deployment_spec_replicas{namespace=~\"openshift-kueue-operator|tekton-kueue\"},\n  1\n) * 100",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Pods Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    container_memory_working_set_bytes{namespace=~\"tekton-kueue|openshift-kueue-operator\", image!=\"\"} \n    * on(container, pod)\n    group_left\n    kube_pod_container_status_ready{namespace=~\"tekton-kueue|openshift-kueue-operator\"}\n)\n    / on (pod) max by (pod) (kube_pod_resource_limit{resource='memory',namespace=~\"tekton-kueue|openshift-kueue-operator\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Admission Latency 99th Percentile",
   "type": "stat",
   "description": "99th Percentile of the latency of an admission attempt.",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(kueue_admission_attempt_duration_seconds_bucket[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    pod:container_cpu_usage:sum{namespace=~\"tekton-kueue|openshift-kueue-operator\"}\n    * on(pod)\n    kube_pod_container_status_ready{namespace=~\"tekton-kueue|openshift-kueue-operator\"}\n) / on (pod) group_right max by (pod) (kube_pod_resource_limit{resource='cpu',namespace=~\"tekton-kueue|openshift-kueue-operator\"}) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kueue Mutating Webhook Request Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(increase(apiserver_admission_webhook_request_total{name=\"pipelinerun-kueue-defaulter.tekton-kueue.io\", code=~\"2..|400\"}[10m]))\n/\nsum(increase(apiserver_admission_webhook_request_total{name=\"pipelinerun-kueue-defaulter.tekton-kueue.io\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tekton Kueue CEL evaluations filiaures",
   "type": "stat",
   "description": "Monitor the overall health and usage of CEL expressions in tekton-kueue webhook",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tekton_kueue_cel_evaluations_total{result=\"failure\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Restarts In the Last Hour",
   "type": "stat",
   "gridPos": { "h": 27, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=~\"tekton-kueue|openshift-kueue-operator\"}[1h])\n* on(container, pod)\nkube_pod_container_status_ready{namespace=~\"tekton-kueue|openshift-kueue-operator\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Cluster Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Queue Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "max by (status) (kueue_cluster_queue_status{cluster_queue=\"cluster-pipeline-queue\"}) == 1",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Pending Workloads",
   "type": "stat",
   "description": "The number of pending workloads",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (status) (kueue_pending_workloads{cluster_queue=\"cluster-pipeline-queue\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Admitted Active Workloads",
   "type": "stat",
   "description": "The number of admitted Workloads that are active (unsuspended and not finished)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kueue_admitted_active_workloads{cluster_queue=\"cluster-pipeline-queue\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Admitted Workloads Increase",
   "type": "stat",
   "description": "The total number of admitted workloads in the selected range",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kueue_admitted_workloads_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Admission Wait Time 99th Percentile ",
   "type": "stat",
   "description": "99% of the workloads waited in the queue less time from the shown value",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(kueue_admission_wait_time_seconds_bucket{cluster_queue=\"cluster-pipeline-queue\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Admitted Workloads Increase By Priority Class",
   "type": "stat",
   "description": "The total number of admitted workloads,  by priority class , in the selected range",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (priority_class) (increase(kueue_admitted_workloads_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Admission Wait Time 99th Percentile By Priority Class",
   "type": "stat",
   "description": "99% of the workloads waited in the queue less time from the shown value. Broke into Priority Classes.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(kueue_admission_wait_time_seconds_bucket{cluster_queue=\"cluster-pipeline-queue\"}[$__range])) by (le, priority_class))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Reservation / Nominal Quota",
   "type": "bargauge",
   "gridPos": { "h": 56, "w": 11, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (resource) (kueue_cluster_queue_resource_reservation{cluster_queue=\"cluster-pipeline-queue\"} /kueue_cluster_queue_nominal_quota{cluster_queue=\"cluster-pipeline-queue\"} * 100)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Resource Usage / Reservation",
   "type": "stat",
   "gridPos": { "h": 56, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (resource) (kueue_cluster_queue_resource_usage{cluster_queue=\"cluster-pipeline-queue\"} / kueue_cluster_queue_resource_reservation{cluster_queue=\"cluster-pipeline-queue\"} * 100)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Admission Wait Time",
   "type": "heatmap",
   "description": "kueue_admission_wait_time_seconds",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 138 },
   "targets": [
    {
     "expr": "sum by (le) (increase(kueue_admission_wait_time_seconds_bucket{cluster_queue=\"cluster-pipeline-queue\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Quota Reserved Wait Time",
   "type": "heatmap",
   "description": "The time between a workload was created or requeued until it got quota reservation",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 153 },
   "targets": [
    {
     "expr": "sum by (le) (increase(kueue_quota_reserved_wait_time_seconds_bucket{cluster_queue=\"cluster-pipeline-queue\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Admission Check Wait Time",
   "type": "heatmap",
   "description": "The time from when a workload got the quota reservation until admission",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 166 },
   "targets": [
    {
     "expr": "sum by (le) (increase(kueue_admission_checks_wait_time_seconds_bucket{cluster_queue=\"cluster-pipeline-queue\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 179 } },
  {
   "title": "Number of Tenants",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 180 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_namespace_labels{label_konflux_ci_dev_type=\"tenant\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Workloads vs Etcd Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 187 },
   "targets": [
    {
     "expr": "max(kueue_admitted_active_workloads{cluster_queue=\"cluster-pipeline-queue\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(etcd_mvcc_db_total_size_in_use_in_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Pipelineruns vs Etcd Usage",
   "type": "timeseries",
   "description": "The number of all the Pipelineruns in the cluster (in all states) vs Etcd usage",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 201 },
   "targets": [
    {
     "expr": "max(apiserver_storage_objects{resource=\"pipelineruns.tekton.dev\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(etcd_mvcc_db_total_size_in_use_in_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Deletion Duration 99th Percentile",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 215 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (increase(watcher_pipelinerun_delete_duration_seconds_bucket[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PipelineRun Deletion Duration",
   "type": "heatmap",
   "description": "The duration that watcher take to delete the PipelineRun since completion",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 221 },
   "targets": [
    {
     "expr": "sum by (le) (increase(watcher_pipelinerun_delete_duration_seconds_bucket[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}