apiVersion: v1
data:
  maxRetention: "30"
  runAt: 5 5 * * 0
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/name: tekton-results-retention-policy
    app.kubernetes.io/part-of: tekton-results
    app.kubernetes.io/version: devel
  name: tekton-results-config-results-retention-policy
  namespace: tekton-results
