apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-infra-deployments/components/monitoring/blackbox-exporter/staging/private/lightwell-dev?ref=8ca73f9cba10dd4ae940137742d7ac8f50a29539

namespace: appstudio-monitoring
