apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-infra-deployments/components/monitoring/blackbox-exporter/staging/private/lightwell-dev?ref=38254989c66b98aeafc51505677a244afd1e1ff8

namespace: appstudio-monitoring
