---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: restrict-bindings-serviceaccounts-create.konflux-ci.dev
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups: ["rbac.authorization.k8s.io"]
      apiVersions: ["v1"]
      operations: ["CREATE"]
      resources: ["rolebindings"]
      scope: "Namespaced"
  variables:
  - name: restrictedServiceAccountsPrefix
    expression: "'konflux-bot-'"
  - name: allowedClusterRoleNamePattern
    expression: "'^konflux-.+-bot-actions$'"
  - name: bindsRestrictedKonfluxBotServiceAccount
    expression: |
      has(object.subjects) &&
      object.subjects.exists(subject,
        subject.kind == 'ServiceAccount' &&
        (!has(subject.apiGroup) || subject.apiGroup == '') &&
        has(subject.name) &&
        subject.name.startsWith(variables.restrictedServiceAccountsPrefix))
  - name: usesForbiddenRoleRef
    expression: |
      has(object.roleRef) && (
        object.roleRef.kind == 'Role' ||
        (object.roleRef.kind == 'ClusterRole' &&
          has(object.roleRef.name) &&
          !object.roleRef.name.matches(variables.allowedClusterRoleNamePattern)))
  validations:
  - expression: |
      !(variables.bindsRestrictedKonfluxBotServiceAccount && variables.usesForbiddenRoleRef)
    reason: Invalid
    messageExpression: |
      "ServiceAccounts with prefix '" +
      variables.restrictedServiceAccountsPrefix +
      "' cannot be bound to a Role and can only be bound to ClusterRoles matching the pattern konflux-*-bot-actions."
    # fall-back if something is wrong with the messageExpression above
    message: |
      ServiceAccounts with prefix 'konflux-bot-' cannot be bound to a Role and can only be bound to ClusterRoles matching the pattern konflux-*-bot-actions.
