apiVersion: v1
kind: ConfigMap
metadata:
  name: image-rbac-proxy
  namespace: image-rbac-proxy
data:
  backend-namespace: redhat-user-workloads
  cluster-url: https://da837cbw0di4ab97asm0.vpe.private.us-east.containers.cloud.ibm.com:31533
  proxy-url: https://image-rbac-proxy.kflux-lw-p01-23c2640bcea594f87bc757d4116925b2-0000.us-east.containers.appdomain.cloud
  dex-url: https://image-rbac-proxy.kflux-lw-p01-23c2640bcea594f87bc757d4116925b2-0000.us-east.containers.appdomain.cloud/idp
