---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deny-unallowed-annotations
  namespace: tekton-kueue
data:
  message-expression: |-
    "PipelineRun validation failed: the cluster doesn't provide the following resources: " +
    variables.difference.map(k, k.replace("kueue.konflux-ci.dev/requests-", "")).join(", ")
  annotation-prefixes: '["kueue.konflux-ci.dev/requests-"]'
  # this field is generated via `hack/kueue-allowed-vms/generate-allowed-annotations.sh`
  allowed-annotations: "[\"kueue.konflux-ci.dev/requests-aws-ip\", \"kueue.konflux-ci.dev/requests-cpu\", \"kueue.konflux-ci.dev/requests-konflux-ci-dev-token\", \"kueue.konflux-ci.dev/requests-konflux-release\", \"kueue.konflux-ci.dev/requests-linux-amd64\", \"kueue.konflux-ci.dev/requests-linux-arm64\", \"kueue.konflux-ci.dev/requests-linux-x86-64\", \"kueue.konflux-ci.dev/requests-local\", \"kueue.konflux-ci.dev/requests-localhost\", \"kueue.konflux-ci.dev/requests-memory\", \"kueue.konflux-ci.dev/requests-mintmaker\"]"
