apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-infra-deployments

resources:
  - authentication
  - etcd-shield
  - konflux-operator
  - kueue
  - kyverno

components:
  - ../../k-components/deploy-to-all-staging-clusters
  - ../../k-components/deploy-to-staging-tenant-clusters
  - ../../k-components/deploy-to-staging-eaas-clusters
  - ../../k-components/deploy-to-staging-internal-tenant-clusters
