apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deny-invalid-build-platforms-validatingadmissionpolicy.yaml
- deny-invalid-build-platforms-validatingadmissionpolicybinding.yaml
