apiVersion: v1
kind: Secret
metadata:
  name: backup-s3-credentials
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id=minioadmin
    aws_secret_access_key=minioadmin
  access_key_id: minioadmin
  secret_access_key: minioadmin
