apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: authentication-rd
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              selector:
                matchLabels:
                  appstudio.redhat.com/is-tenant-cluster: "true"
              values:
                sourceRoot: components/authentication-rd
                ring: "ring-0"
                clusterDir: base
          - list:
              elements:
                # Ring 1
                - values.ring: ring-1
                  nameNormalized: stone-stage-p01
                  values.clusterDir: stone-stage-p01
                - values.ring: ring-1
                  nameNormalized: stone-stg-rh01
                  values.clusterDir: stone-stg-rh01
                - values.ring: ring-1
                  nameNormalized: kflux-stg-es01
                  values.clusterDir: kflux-stg-es01
                # Ring 2
                - values.ring: ring-2
                  nameNormalized: kflux-fedora-01
                  values.clusterDir: kflux-fedora-01
                - values.ring: ring-2
                  nameNormalized: kflux-ocp-p01
                  values.clusterDir: kflux-ocp-p01
                - values.ring: ring-2
                  nameNormalized: kflux-osp-p01
                  values.clusterDir: kflux-osp-p01
                - values.ring: ring-2
                  nameNormalized: kflux-prd-es01
                  values.clusterDir: kflux-prd-es01
                - values.ring: ring-2
                  nameNormalized: kflux-prd-rh03
                  values.clusterDir: kflux-prd-rh03
                - values.ring: ring-2
                  nameNormalized: kflux-rhel-p01
                  values.clusterDir: kflux-rhel-p01
                - values.ring: ring-2
                  nameNormalized: stone-prod-p01
                  values.clusterDir: stone-prod-p01
                # Ring 3
                - values.ring: ring-3
                  nameNormalized: stone-prd-rh01
                  values.clusterDir: stone-prd-rh01
                - values.ring: ring-3
                  nameNormalized: stone-prod-p02
                  values.clusterDir: stone-prod-p02
                # Ring 4
                - values.ring: ring-4
                  nameNormalized: kflux-prd-rh02
                  values.clusterDir: kflux-prd-rh02
  template:
    metadata:
      name: authentication-rd-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/rings/{{values.ring}}/{{values.clusterDir}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: authentication
        server: '{{server}}'
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 15s
