apiVersion: konflux.konflux-ci.dev/v1alpha1
kind: Konflux
metadata:
  name: konflux
spec:
  info:
    spec:
      publicInfo:
        visibility: private
        statusPageUrl: "https://grafana.app-sre.devshift.net/d/aes1ns0htwni8a/konflux-status-page?var-cluster=lightwell-dev"
        integrations:
          github:
            application_url: "https://github.com/apps/lightwell-dev"
