apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - https://github.com/redhat-appstudio/internal-infra-deployments/components/monitoring/blackbox-exporter/production/private/kflux-ocp-p01?ref=5a73e4e02c28abba6334dc04bc4c339b49cafbe3

namespace: appstudio-monitoring
