apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - https://github.com/redhat-appstudio/internal-infra-deployments/components/monitoring/blackbox-exporter/production/private/kflux-ocp-p01?ref=a15283b119f02fe724b8fd2af065602f2f087a46

namespace: appstudio-monitoring
