environment: "stage"

#localPlatforms:
#  - "linux/amd64"
#  - "linux/x86_64"
#  - "local"
#  - "localhost"

instanceTag: "lightwell-dev"

additionalInstanceTags:
  service-phase: "Staging"

archDefaults:
  arm64:
    ami: "ami-06f37afe6d4f43c47"
    key-name: "konflux-stage-ext-mab01"
    security-group-id: "sg-05f1da470c716c603"
    subnet-id: "subnet-0958667237f37416a"
  amd64:
    ami: "ami-01aaf1c29c7e0f0af"
    key-name: "konflux-stage-ext-mab01"
    security-group-id: "sg-05f1da470c716c603"
    subnet-id: "subnet-0958667237f37416a"

dynamicConfigs:
  linux-arm64:
    subnet-id: "subnet-01b88957a67590dc2"

  linux-amd64:
    subnet-id: "subnet-06132f7bf72af6ce6"

  linux-root-arm64:
    sudo-commands: "/usr/bin/podman"
    disk: "200"

  linux-root-amd64:
    sudo-commands: "/usr/bin/podman"
    disk: "200"
    # user-data loaded from ../staging/base/host-config-chart/files/linux-root-amd64-init.sh



# Static hosts configuration
staticHosts:

