resources:
  - ../base
  - cronjobs

patches:
  # Kanary V1
  - path: external-secrets/patches/kanary-probe-prometheus-credentials-path.yaml
    target:
      name: kanary-probe-prometheus-credentials
      kind: ExternalSecret
      group: external-secrets.io
      version: v1
  - path: external-secrets/patches/kanary-probe-users-credentials-path.yaml
    target:
      name: kanary-probe-users-credentials-tenant4
      kind: ExternalSecret
      group: external-secrets.io
      version: v1
  - path: external-secrets/patches/kanary-probe-users-credentials-tenant3-path.yaml
    target:
      name: kanary-probe-users-credentials-tenant3
      kind: ExternalSecret
      group: external-secrets.io
      version: v1
