apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: invalid-konflux-bot-role-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-test-role
subjects:
- kind: ServiceAccount
  name: konflux-bot-0
