apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    paas.redhat.com/appcode: MINT-001
resources:
  - ../../base
  - ../../base/external-secrets
  - https://github.com/konflux-ci/mintmaker/config/default?ref=b8b7c25d43e264c57632518a085d4a01a28f7df4
  - https://github.com/konflux-ci/mintmaker/config/renovate?ref=b8b7c25d43e264c57632518a085d4a01a28f7df4

namespace: mintmaker

images:
  - name: quay.io/konflux-ci/mintmaker
    newName: quay.io/konflux-ci/mintmaker
    newTag: b8b7c25d43e264c57632518a085d4a01a28f7df4
  - name: quay.io/konflux-ci/mintmaker-renovate-image
    newName: quay.io/konflux-ci/mintmaker-renovate-image
    newTag: b5a8b2983f16858b8b92ee5f51769f5707b2aaf3
  - name: quay.io/konflux-ci/mintmaker-schedule-calculator
    newName: quay.io/konflux-ci/mintmaker-schedule-calculator
    newTag: dcda93c47b269d9b250ef62b0bd2e2e2f18aea6f

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

configMapGenerator:
  - name: controller-config
    files:
    - config.json

patches:
  - path: manager-mount-config-patch.yaml
  - path: pipelines-as-code-secret-path.yaml
    target:
      name: pipelines-as-code-secret
      kind: ExternalSecret
      group: external-secrets.io
      version: v1
  - path: manager-set-resources-patch.yaml

configurations:
- kustomizeconfig.yaml

components:
  - ../../components/rh-certs
