apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    paas.redhat.com/appcode: MINT-001
resources:
  - ../../base
  - ../../base/external-secrets
  - https://github.com/konflux-ci/mintmaker/config/default?ref=c8d93fd9fbbe59b2cb567a319af71a156b1d788d
  - https://github.com/konflux-ci/mintmaker/config/renovate?ref=c8d93fd9fbbe59b2cb567a319af71a156b1d788d

namespace: mintmaker

images:
  - name: quay.io/konflux-ci/mintmaker
    newName: quay.io/konflux-ci/mintmaker
    newTag: c8d93fd9fbbe59b2cb567a319af71a156b1d788d
  - name: quay.io/konflux-ci/mintmaker-renovate-image
    newName: quay.io/konflux-ci/mintmaker-renovate-image
    newTag: 5fa9e2f0134e156c6430eac52c16b8010f489539

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

configMapGenerator:
  - name: controller-config
    files:
    - config.json

patches:
  - path: manager-mount-config-patch.yaml
  - path: pipelines-as-code-secret-path.yaml
    target:
      name: pipelines-as-code-secret
      kind: ExternalSecret
      group: external-secrets.io
      version: v1
  - path: manager-set-resources-patch.yaml
  - path: suspend-dependency-check-patch.yaml

configurations:
- kustomizeconfig.yaml

components:
  - ../../components/rh-certs
