apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    paas.redhat.com/appcode: MINT-001
resources:
  - ../../base
  - ../../base/external-secrets
  - https://github.com/konflux-ci/mintmaker/config/default?ref=30c16866eab1dd107f780004d9ce784266dba783
  - https://github.com/konflux-ci/mintmaker/config/renovate?ref=30c16866eab1dd107f780004d9ce784266dba783

namespace: mintmaker

images:
  - name: quay.io/konflux-ci/mintmaker
    newName: quay.io/konflux-ci/mintmaker
    newTag: 30c16866eab1dd107f780004d9ce784266dba783
  - name: quay.io/konflux-ci/mintmaker-renovate-image
    newName: quay.io/konflux-ci/mintmaker-renovate-image
    newTag: 63f76fa2b0f1fec33e6138a09cde9f745130cbbd

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

configMapGenerator:
  - name: controller-config
    files:
    - config.json

patches:
  - path: manager-mount-config-patch.yaml
  - path: pipelines-as-code-secret-path.yaml
    target:
      name: pipelines-as-code-secret
      kind: ExternalSecret
      group: external-secrets.io
      version: v1
  - path: manager-set-resources-patch.yaml

configurations:
- kustomizeconfig.yaml

components:
  - ../../components/rh-certs
