apiVersion: v1
kind: Namespace
metadata:
  name: konflux-conformance-tests
  labels:
    konflux-ci.dev/type: tenant
    cost-center: "670"
    cost_management_optimizations: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: konflux-managed-tests
