apiVersion: v1
kind: ServiceAccount
metadata:
  name: konflux-bot-0
  namespace: konflux-managed-tests
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: konflux-bot-0
  name: konflux-bot-0-token
  namespace: konflux-managed-tests
type: kubernetes.io/service-account-token
