{
 "title": "Sandbox - Usage",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Active User Signups per Cluster",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sandbox_user_accounts_current)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(sandbox_user_accounts_current{cluster_name=\"member-sandbox-stage.gb17.p1.openshiftapps.com\"})",
     "legendFormat": "member-1"
    }
   ]
  },
  {
   "title": "User Lifecycles",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(sandbox_user_signups_approved_total[1d]))*60*60*24",
     "legendFormat": "Approved in the last 24h"
    },
    {
     "expr": "sum by (namespace) (rate(sandbox_user_signups_deactivated_total[1d]))*60*60*24",
     "legendFormat": "Deactivated in the last 24h"
    },
    {
     "expr": "sum by (namespace) (rate(sandbox_user_signups_banned_total[1d]))*60*60*24",
     "legendFormat": "Banned in the last 24h"
    }
   ]
  },
  {
   "title": "Unverified User Signups deleted in the last 24hrs",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(sandbox_user_signups_deleted_with_initiating_verification_total[1d]))*60*60*24",
     "legendFormat": "with phone verification initiated"
    },
    {
     "expr": "sum by (namespace) (rate(sandbox_user_signups_deleted_without_initiating_verification_total[1d]))*60*60*24",
     "legendFormat": "without phone verification initiated"
    }
   ]
  },
  {
   "title": "Active Users Signups per Domain",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sandbox_master_user_records{domain=\"external\"}) or vector(0)",
     "legendFormat": "External users"
    },
    {
     "expr": "sum(sandbox_master_user_records{domain=\"internal\"}) or vector(0)",
     "legendFormat": "Internal users"
    }
   ]
  },
  {
   "title": "All-time User Signups per Domain",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sandbox_users_per_activations_and_domain{domain=\"external\"} or vector(0))",
     "legendFormat": "External users"
    },
    {
     "expr": "sum(sandbox_users_per_activations_and_domain{domain=\"internal\"} or vector(0))",
     "legendFormat": "Internal users"
    }
   ]
  },
  {
   "title": "All-time Users per Activations and Domain",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "sandbox_users_per_activations_and_domain"
    }
   ]
  }
 ]
}