apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/build-service/config/default?ref=8917937f45966a7db5abe10335e08434dfd7f658

namespace: build-service

images:
- name: quay.io/konflux-ci/build-service
  newName: quay.io/konflux-ci/build-service
  newTag: 8917937f45966a7db5abe10335e08434dfd7f658

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

components:
  - ../../components/rh-certs

patches:
  - path: manager_resources_patch.yaml
