apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/build-service/config/default?ref=2d761643b30f58b78c5d017a769a8027f7982433

namespace: build-service

images:
- name: quay.io/konflux-ci/build-service
  newName: quay.io/konflux-ci/build-service
  newTag: 2d761643b30f58b78c5d017a769a8027f7982433

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

components:
  - ../../components/rh-certs

patches:
  - path: manager_resources_patch.yaml
