apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - delete-snapshots.yaml
  - manage-integrationtestscenarios.yaml
  - manage-resolutionrequests.yaml
  - modify-pipelineruns-taskruns.yaml
  - integration-service-maintainers.yaml
