apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets-operator

resources:
- networkpolicy-default-deny.yaml
- networkpolicy-allow-egress.yaml
- networkpolicy-allow-ingress.yaml
- networkpolicy-allow-same-ns.yaml

helmGlobals:
  chartHome: .

helmCharts:
- name: external-secrets
  releaseName: external-secrets-operator
  namespace: external-secrets-operator
  valuesFile: values.yaml

# Override the ESO image with the Konflux-built image
images:
- name: ghcr.io/external-secrets/external-secrets
  newName: quay.io/konflux-ci/external-secrets-operator
  newTag: e42d02f3f5c37a7b4b231e8d5496c74e93074ceb
