apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-rbac-proxy
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/image-rbac-proxy/deploy/base?ref=b74bc7e7fbf366e29e8dcacb9a1e52227833647a

images:
- name: quay.io/konflux-ci/image-rbac-proxy
  newName: quay.io/konflux-ci/image-rbac-proxy
  newTag: b74bc7e7fbf366e29e8dcacb9a1e52227833647a
