apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base-snapshot
- patches

patches:
- target:
    kind: ClusterPolicy
    name: init-ns-integration
  patch: |-
    - op: remove
      path: /spec/rules/0/preconditions
    - op: remove
      path: /spec/rules/1/preconditions
