---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kubearchive.yaml
components:
  - ../../../../k-components/inject-infra-deployments-repo-details
  - ../../../../k-components/deploy-to-member-cluster-merge-generator
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: kubearchive
    patch: |-
      - op: add
        path: /spec/generators/0/merge/generators/1
        value:
          clusters:
            selector:
              matchLabels:
                appstudio.redhat.com/cluster-type: "tenant"
            values:
              sourceRoot: components/kubearchive
              environment: staging
              clusterDir: ""
