apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- limit-serviceaccount-tokenrequest-expiration-validationadmissionpolicy.yaml
- limit-serviceaccount-tokenrequest-expiration-validationadmissionpolicybinding.yaml
