apiVersion: v1
kind: ConfigMap
metadata:
  name: kanary-workspace-vct
data:
  vct.yaml: |
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
