{
 "title": "Namespace Lister Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "HTTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "95 quantile of list-workspace requests",
   "type": "timeseries",
   "description": "p95 latency of requests to list workspaces",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, code) (rate(namespace_lister_api_latency_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time of list-workspace",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(code) (rate(namespace_lister_api_latency_sum[5m])) / sum by(code) (rate(namespace_lister_api_latency_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AccessCache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Average number of namespaces per subjects",
   "type": "stat",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_lister_accesscache_subject_namespace_pairs)/sum(namespace_lister_accesscache_subjects)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subject types",
   "type": "stat",
   "description": "The subjects grouped by type for which the cache is storing access data",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (subject_gk) (namespace_lister_accesscache_subject_namespace_pairs) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subjects per pod",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_lister_accesscache_subjects) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(Subject, Namespace) pairs per pod",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_lister_accesscache_subject_namespace_pairs) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failures synching cache per pod",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_lister_accesscache_synch_op_total{status=\"failed\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed synch operations rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(rate(namespace_lister_accesscache_synch_op_total{status=\"completed\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed synch operations rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum(rate(namespace_lister_accesscache_synch_op_total{status=\"failed\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "time-triggered synch request rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(rate(namespace_lister_accesscache_time_requests_total[$__rate_interval])) by(pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "resource event-triggered synch request rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "sum(rate(namespace_lister_accesscache_resource_requests_total[$__rate_interval])) by(pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(Subject,Namespace) pairs in cache over-time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum(namespace_lister_accesscache_subject_namespace_pairs) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subjects in cache over-time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "sum(namespace_lister_accesscache_subjects) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}