# ServiceAccount for Kargo verification conformance tests.
#
# To generate a long-lived token after deployment:
#   oc -n conformance-managed-tenant create token conformance-verification-sa --duration "$((24*365))h"
# Store the token in Vault: stonesoup/staging/devprod/conformance-verification-sa
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conformance-verification-sa
  namespace: conformance-managed-tenant
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: conformance-verification-sa
  name: conformance-verification-sa-token
  namespace: conformance-managed-tenant
type: kubernetes.io/service-account-token
