apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- https://github.com/flacatus/konflux-dummy-deploy//k8s?ref=0ef13edf7fbafac1611c94579a2dad3f038f16b5
images:
- name: quay.io/redhat-appstudio-qe/dummy-deployment
  newTag: 0ef13edf7fbafac1611c94579a2dad3f038f16b5
patches:
- target:
    kind: ConfigMap
    name: dummy-deployment-config
  patch: |
    - op: replace
      path: /data/DISPLAY_TEXT
      value: "Hello from DEVELOPMENT!"
