apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- https://github.com/flacatus/konflux-dummy-deploy//k8s?ref=c810dfb24d99ff56376cd351ff03833e2de4fa22
images:
- name: quay.io/redhat-appstudio-qe/dummy-deployment
  newTag: c810dfb24d99ff56376cd351ff03833e2de4fa22
patches:
- target:
    kind: ConfigMap
    name: dummy-deployment-config
  patch: |
    - op: replace
      path: /data/DISPLAY_TEXT
      value: "Hello from DEVELOPMENT!"
