
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-3"
  name: redhat-operators-1-18
  namespace: openshift-kueue-operator
spec:
  displayName: redhat-operators-1-18
  image: registry.redhat.io/redhat/redhat-operator-index:v4.18
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m
