apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- project-controller-maintainers-rb.yaml
- grant-argocd-rb.yaml
- crd-manager-project-controller-crb.yaml

namespace: project-controller
