apiVersion: konflux.konflux-ci.dev/v1alpha1
kind: Konflux
metadata:
  name: konflux
spec:
  certManager:
    createClusterIssuer: true
  internalRegistry:
    enabled: false
  defaultTenant:
    enabled: false
