---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-reader
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-reader
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    kubernetes.io/service-account.name: metrics-reader
type: kubernetes.io/service-account-token
