apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - https://github.com/redhat-appstudio/internal-infra-deployments/components/monitoring/blackbox-exporter/production/public/kflux-fedora-01?ref=86797d1ff34bc9fa9619172f05e56f4b4476e210

namespace: appstudio-monitoring
