---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.konflux-ci.dev/aggregate-to-maintainer: "true"
  name: konflux-maintainer-releaseplanadmissions.appstudio.redhat.com
rules:
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - releaseplanadmissions
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
