apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-infra-deployments/components/repository-validator/staging?ref=c7cb8d9b6767871224fa229dda69135e0a4710df
  - ../base
