apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-infra-deployments/components/repository-validator/staging?ref=70803ec2c18ed82c956be71b6292ff41592b36e0
  - ../base
