apiVersion: konflux.konflux-ci.dev/v1alpha1
kind: Konflux
metadata:
  name: konflux
spec:
  imageController:
    # patched by hack/preview.sh if IMAGE_CONTROLLER_QUAY_ORG and
    # IMAGE_CONTROLLER_QUAY_TOKEN are set
    enabled: false
