apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base-snapshot

patches:
  - path: image-patch.yaml
    target:
      kind: CronJob
      name: etcd-maintenance
  - path: patches/schedule-patch.yaml
    target:
      kind: CronJob
      name: etcd-maintenance
