apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/minio/operator?ref=v5.0.15
  - base-snapshot
  - rbac
  - secrets
  - minio-tenant.yaml
  - minio-create-bucket-job.yaml
  - tekton-chains-signing-secret-job.yaml

patches:
  - path: patches/delete-tekton-results-configmap-patch.yaml
  - path: patches/delete-tekton-results-database-es-patch.yaml
  - path: patches/delete-tekton-results-s3-es-patch.yaml
  - path: patches/delete-chains-public-key-es-patch.yaml
  - path: patches/delete-chains-signing-secret-es-patch.yaml
  - path: patches/delete-tekton-logging-resources-patch.yaml
  - path: patches/delete-testing-ns-patch.yaml
  - path: patches/delete-testing-sa-patch.yaml
  - path: patches/delete-testing-crb-patch.yaml
  - path: patches/delete-testing-rb-patch.yaml
  - path: patches/add-argocd-skip-dry-run-annotation-patch.yaml

  # Service exporter settings
  - path: patches/service-exporter-resources.yaml
    target:
      kind: Deployment
      name: pipeline-metrics-exporter
      namespace: openshift-pipelines

  # TektonConfig changes
  - path: patches/tektonconfig-resources-updates.yaml
  - path: patches/tektonconfig-pipeline-configmaps.yaml
    target:
      kind: TektonConfig
      name: config
  - path: patches/tektonconfig-disable-pruner.yaml
    target:
      kind: TektonConfig
      name: config
  # remove PaC resources
  - target:
      kind: TektonConfig
      name: config
    patch: |
      - op: remove
        path: /spec/platforms/openshift/pipelinesAsCode/options/deployments/pipelines-as-code-controller
      - op: remove
        path: /spec/platforms/openshift/pipelinesAsCode/options/deployments/pipelines-as-code-watcher/spec/template
      - op: remove
        path: /spec/platforms/openshift/pipelinesAsCode/options/deployments/pipelines-as-code-webhook/spec/template
  # Disable TektonResults DB
  - target:
      kind: TektonConfig
      name: config
    patch: |
      - op: replace
        path: /spec/result/is_external_db
        value: false
      - op: remove
        path: /spec/result/db_port
      - op: remove
        path: /spec/result/db_secret_name
      - op: remove
        path: /spec/result/db_secret_password_key
      - op: remove
        path: /spec/result/db_secret_user_key
      - op: remove
        path: /spec/result/db_sslmode
      - op: remove
        path: /spec/result/db_sslrootcert
      - op: remove
        path: /spec/result/db_enable_auto_migration
      # kube-rbac-proxy not in dev (unknown why)
      - op: remove
        path: /spec/result/options/deployments/tekton-results-api/spec/template/spec/containers/1
      - op: remove
        path: /spec/result/options/deployments/tekton-results-watcher/spec/template/spec/containers/1
      # logging plugin api url and db env are not in dev (unknown why)
      # note: all env here are `0` because the remove acts as a "pop"
      - op: remove
        path: /spec/result/options/deployments/tekton-results-api/spec/template/spec/containers/0/env/0
      - op: remove
        path: /spec/result/options/deployments/tekton-results-api/spec/template/spec/containers/0/env/0
      - op: remove
        path: /spec/result/options/deployments/tekton-results-api/spec/template/spec/containers/0/env/0
      # adjust store dealine
      - op: replace
        path: /spec/result/options/deployments/tekton-results-watcher/spec/template/spec/containers/0/args/0
        value: "-completed_run_grace_period=2h"
      - op: replace
        path: /spec/result/options/deployments/tekton-results-watcher/spec/template/spec/containers/0/args/1
        value: "-requeue_interval=2m"
      - op: replace
        path: /spec/result/options/deployments/tekton-results-watcher/spec/template/spec/containers/0/args/2
        value: "-store_deadline=1m"
      # Configure minio S3 cert
      - op: replace
        path: /spec/result/options/deployments/tekton-results-api/spec/template/spec/volumes/0
        value:
          name: ca-s3
          secret:
            items:
              - key: public.crt
                path: s3-cert.crt
            secretName: storage-tls
      - op: replace
        path: /spec/result/options/deployments/tekton-results-api/spec/template/spec/containers/0/volumeMounts/0
        value:
          name: ca-s3
          mountPath: /etc/ssl/certs/s3-cert.crt
          subPath: s3-cert.crt
  - path: patches/tektonconfig-results-resources.yaml
    target:
      kind: TektonConfig
      name: config

  # Minio requires patching even though it's only in ring 0 because it's provided
  # via the helm chart.
  # Minio operator services
  - path: patches/minio-patches/add-dangling-service-annotation.yaml
    target:
      kind: Service
      name: operator
      namespace: minio-operator
  # Minio operator deployments
  - path: patches/minio-patches/update-minio-operator-image-patch.yaml
    target:
      kind: Deployment
      name: minio-operator
      namespace: minio-operator
  - path: patches/minio-patches/remove-containers-security-context-patch.yaml
    target:
      kind: Deployment
      name: minio-operator
      namespace: minio-operator
  - path: patches/minio-patches/add-template-argocd-sync-options-annotation-patch.yaml
    target:
      kind: Deployment
      name: minio-operator
      namespace: minio-operator
  - path: patches/minio-patches/add-read-only-root-fs-annotation-patch.yaml
    target:
      kind: Deployment
      name: minio-operator
      namespace: minio-operator
  - path: patches/minio-patches/update-replicas-count-patch.yaml
    target:
      kind: Deployment
      name: minio-operator
      namespace: minio-operator
  # --- Minio operator deployment resources limits & requests
  - target:
      kind: Deployment
      name: minio-operator
      namespace: minio-operator
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: 200m
          memory: 256Mi
      - op: add
        path: /spec/template/spec/containers/0/resources/requests
        value:
          cpu: 50m
          memory: 128Mi
  # Console deployment
  - path: patches/minio-patches/update-minio-operator-image-patch.yaml
    target:
      kind: Deployment
      name: console
      namespace: minio-operator
  - path: patches/minio-patches/remove-containers-security-context-patch.yaml
    target:
      kind: Deployment
      name: console
      namespace: minio-operator
  - path: patches/minio-patches/add-template-argocd-sync-options-annotation-patch.yaml
    target:
      kind: Deployment
      name: console
      namespace: minio-operator
  - path: patches/minio-patches/add-containers-fs-security-context-patch.yaml
    target:
      kind: Deployment
      name: console
      namespace: minio-operator
  # --- Console deployment resources limits & requests
  - target:
      kind: Deployment
      name: console
      namespace: minio-operator
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
