apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
  name: tekton-chains-signing-secret
  namespace: openshift-pipelines
spec:
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          set -o errexit
          set -o nounset
          set -o pipefail

          namespace="openshift-pipelines"
          secret="signing-secrets"

          cd /tmp

          if [ "$(kubectl get secret "$secret" -n "$namespace" -o jsonpath='{.data}' --ignore-not-found --allow-missing-template-keys)" != "" ]; then
            echo "Signing secret exists and is non-empty."
          else
            # Delete secret/signing-secrets if already exists since by default cosign creates immutable secrets
            kubectl delete secrets "$secret" -n "$namespace" --ignore-not-found=true

            # To make this run conveniently without user input let's create a random password
            RANDOM_PASS=$( openssl rand -base64 30 )

            # Generate the key pair secret directly in the cluster.
            # The secret should be created as immutable.
            echo "Generating k8s secret/$secret in $namespace with key-pair"
            env COSIGN_PASSWORD=$RANDOM_PASS cosign generate-key-pair "k8s://$namespace/$secret"
          fi

          echo "Generating/updating the secret with the public key"
          kubectl create secret generic public-key \
            --namespace "$namespace" \
            --from-literal=cosign.pub="$(
              cosign public-key --key "k8s://$namespace/$secret"
            )" \
            --dry-run=client \
            -o yaml | kubectl apply -f -
        image: quay.io/konflux-ci/appstudio-utils:ab6b0b8e40e440158e7288c73aff1cf83a2cc8a9@sha256:24179f0efd06c65d16868c2d7eb82573cce8e43533de6cea14fec3b7446e0b14
        imagePullPolicy: Always
        name: chains-secret-generation
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: chains-secrets-admin
      serviceAccountName: chains-secrets-admin
      terminationGracePeriodSeconds: 30
