apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: tekton-results-watcher
    app.kubernetes.io/part-of: tekton-results
    app.kubernetes.io/version: devel
  name: tekton-results-watcher
  namespace: tekton-results
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tekton-results-watcher
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app.kubernetes.io/name: tekton-results-watcher
        app.kubernetes.io/version: devel
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: NotIn
                    values:
                      - windows
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: tekton-results-watcher
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - args:
            - -api_addr
            - tekton-results-api-service-for-watcher.tekton-results.svc.cluster.local:8080
            - -auth_mode
            - token
            - -check_owner=false
            - -completed_run_grace_period=2h
            - -requeue_interval=2m
            - -store_deadline=1m
            - -forward_buffer=1m
            - -threadiness=32
            - -qps=50
            - -burst=50
            - -logs_api=true
            - -disable_storing_incomplete_runs=true
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: tekton-results-config-logging
            - name: CONFIG_LEADERELECTION_NAME
              value: tekton-results-config-leader-election
            - name: CONFIG_OBSERVABILITY_NAME
              value: tekton-results-config-observability
            - name: METRICS_DOMAIN
              value: tekton.dev/results
            - name: TEKTON_RESULTS_API_SERVICE
              value: tekton-results-api-service-for-watcher.tekton-results.svc.cluster.local:8080
            - name: AUTH_MODE
              value: token
            - name: KUBERNETES_MIN_VERSION
              value: "v1.28.0"
          image: quay.io/konflux-ci/tekton-results-watcher:99db802a56c3d62e823e162feee9811e55ed1f5b
          name: watcher
          ports:
            - containerPort: 9090
              name: metrics
            - containerPort: 8008
              name: profiling
          resources:
            limits:
              cpu: 250m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /etc/tls
              name: tls
              readOnly: true
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:9090/
            - --logtostderr=true
            - --v=6
          image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.12
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: watchermetrics
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      serviceAccountName: tekton-results-watcher
      volumes:
        - name: tls
          secret:
            secretName: tekton-results-for-watcher-tls
