---
- op: replace
  path: /spec/prometheusConfig/remoteWrite
  value:
    # Tekton pipeline metrics
    - url: https://observatorium-mst.api.stage.openshift.com/api/metrics/v1/rhtap/api/v1/receive
      oauth2:
        clientId:
          secret:
            key: client-id
            name: rhobs
        clientSecret:
          key: client-secret
          name: rhobs
        endpointParams:
          audience: observatorium-osd-staging
        tokenUrl: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
      writeRelabelConfigs:
        - action: Keep
          sourceLabels: [__name__]
          regex: "tekton_pipelines_controller_pipelinerun_total\
            |tekton_pipelines_controller_pipelinerun_duration_seconds_sum\
            |tekton_pipelines_controller_pipelinerun_duration_seconds_count\
            |tekton_pipelines_controller_running_pipelineruns\
            |tekton_pipelines_controller_running_pipelineruns_waiting_on_pipeline_resolution\
            |tekton_pipelines_controller_running_pipelineruns_waiting_on_task_resolution\
            |tekton_pipelines_controller_taskrun_total\
            |tekton_pipelines_controller_running_taskruns\
            |tekton_pipelines_controller_running_taskruns_throttled_by_node\
            |tekton_pipelines_controller_running_taskruns_throttled_by_quota"
        - action: LabelKeep
          regex: "__name__|source_environment|source_cluster|namespace|job|instance|pipeline|status|task"
