apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - invariant

components:
  - ../../../base/cr/default-tenant
  - ../../../base/cr/build
  - ../../../base/cr/image-controller
  - ../../../base/cr/integration
  - ../../../base/cr/konflux-info
  - ../../../base/cr/konflux-ui
  - ../../../base/cr/namespace-lister
  - ../../../base/cr/release
  - ../../../base/cr/enterprise-contract
