apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: konflux-viewer-bot-actions
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - taskruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applications
  - snapshots
  - releases
  - components
  - componentgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - konflux-ci.dev
  resources:
  - componentgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pipelinesascode.tekton.dev
  resources:
  - repositories
  verbs:
  - get
  - list
  - watch
