apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-secret-store
  labels: # Helps k-components detect this appset to apply the correct patches
    appstudio.redhat.com/deployment-clusters: "tenant"
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              selector:
                matchExpressions: # Ensures that no clusters are selected; k-components will replace this
                  - key: appstudio.redhat.com/select-none
                    operator: Exists
                  - key: appstudio.redhat.com/select-none
                    operator: DoesNotExist
              values:
                sourceRoot: components/cluster-secret-store-rd
                ring: "empty-base"
                clusterDir: "empty-base"
          - list:
              elements: [] # Populated via k-components
  template:
    metadata:
      name: cluster-secret-store-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/rings/{{values.ring}}/{{values.clusterDir}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: cluster-secret-store
        server: '{{server}}'
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 15s
