apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: konflux-disaster-recovery

resources:
- konflux-disaster-recovery-ns.yaml
- dr-sanity-runner-sa.yaml
- dr-preflight-task.yaml
- dr-baseline-run-task.yaml
- dr-backup-task.yaml
- dr-disaster-and-restore-task.yaml
- dr-post-restore-verify-task.yaml
- dr-cleanup-task.yaml
- dr-sanity-pipeline.yaml
