apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/konflux-ci/konflux-ci/operator/config/default?ref=a5d8ef4843a20ff4b3c72cd4db21b3456868825a
  - konflux.yaml

images:
  - name: localhost/konflux-operator
    newName: quay.io/konflux-ci/konflux-operator
    newTag: a5d8ef4843a20ff4b3c72cd4db21b3456868825a
