apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/konflux-ci/konflux-ci/operator/config/default?ref=bbf23e4ac2610c8c55a1a4e0e5954ee1222b93ad
  - konflux.yaml

images:
  - name: localhost/konflux-operator
    newName: quay.io/konflux-ci/konflux-operator
    newTag: bbf23e4ac2610c8c55a1a4e0e5954ee1222b93ad
