apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- metrics-reader-sa.yaml
- metrics-reader-secret.yaml
- prometheus-multi-platform-controller-metrics-reader-crb.yaml
- multi-platform-controller-metrics-monitor-sm.yaml
