apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: disaster-recovery
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: appstudio.redhat.com/select-none
                    operator: Exists
                  - key: appstudio.redhat.com/select-none
                    operator: DoesNotExist
              values:
                sourceRoot: components/disaster-recovery
                ring: empty-base
                clusterDir: "empty-base"
          - list:
              elements: []
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: disaster-recovery-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/rings/{{values.ring}}/{{values.clusterDir}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: konflux-disaster-recovery
        server: '{{server}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
