kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: monitoring-cardinality
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              values:
                sourceRoot: components/monitoring/cardinality
                environment: staging
                clusterDir: ""
          - list:
              elements:
                - nameNormalized: stone-prd-rh01
                  values.clusterDir: stone-prd-rh01
                  values.environment: production
                - nameNormalized: kflux-prd-rh02
                  values.clusterDir: kflux-prd-rh02
                  values.environment: production
  template:
    metadata:
      name: monitoring-cardinality-{{nameNormalized}}
    spec:
      project: default
      source:
        path: "{{values.sourceRoot}}/{{values.environment}}/{{values.clusterDir}}"
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: appstudio-cardinality-exporter
        server: "{{server}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 15s
