---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: miniojobs.job.min.io
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: policybindings.sts.min.io
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenants.minio.min.io
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: console-sa
  namespace: minio-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-operator
  namespace: minio-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: console-sa-role
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-sa-binding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minio-operator-role
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minio-operator-binding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-minio-apply-tenants
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-minio-apply-tenants
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: console-env
  namespace: minio-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: v1
kind: Secret
metadata:
  name: console-sa-secret
  namespace: minio-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: v1
kind: Service
metadata:
  name: console
  namespace: minio-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: v1
kind: Service
metadata:
  name: operator
  namespace: minio-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: v1
kind: Service
metadata:
  name: sts
  namespace: minio-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: minio-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  namespace: minio-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
