apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-conformance-sa-token
  namespace: konflux-managed-tests
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: appsre-stonesoup-vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: konflux-bot-0-token
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: staging/devprod/konflux-sa-rd-lightwell-dev
          property: token
