apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ../base/cost-management
- ../policies/kueue/
- ../policies/kubearchive/

# Rollout to Ring 1.
# Ring 3's rollout will remove it and add it to base's directly
- ../base/konflux-rbac/restrict-binding-serviceaccounts/
