apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - https://github.com/redhat-appstudio/internal-infra-deployments/components/monitoring/blackbox-exporter/production/private/kflux-rhel-p01?ref=57ee9093ab7539f7f273b0754e0d66375aa32205

namespace: appstudio-monitoring
