---
# Tempo is excluded from the production
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tempo
$patch: delete
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nvme-storage-configurator
$patch: delete
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-workload-custom-kube-state-metrics
$patch: delete
---
# Cardinality exporter is staging-only
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-cardinality
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: disaster-recovery
$patch: delete
