resources:
- internal_service_request_role.yaml
- internal_service_request_role_binding.yaml
- internal_service_request_service_account.yaml
- internal_service_service_account_token.yaml
- internal-services.yaml
- https://github.com/konflux-ci/internal-services/config/crd?ref=a8de214720c7bb2dd0b0f629067b0a06fe427b78

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: internal-services
