resources:
- internal_service_request_role.yaml
- internal_service_request_role_binding.yaml
- internal_service_request_service_account.yaml
- internal_service_service_account_token.yaml
- internal-services.yaml
- https://github.com/konflux-ci/internal-services/config/crd?ref=05fe8370ac9254a08c0b44fad1de119030cc4045

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: internal-services
