apiVersion: v1
kind: ResourceQuota
metadata:
  name: internal-services
  namespace: internal-services
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    count/jobs.batch: "500"
