apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
# Remove this comment to rotate dex and proxy secrets
#  - configure-oauth-proxy-secret.yaml

configMapGenerator:
  - name: dex
    files:
      - dex-config.yaml
  - name: ui-runtime-env-variables
    literals:
      - MONITORING_ENABLED=true
      - MONITORING_DSN=https://2d1bbbd05a2ff473d916df439cfc363e@o490301.ingest.us.sentry.io/4510260965408768
      - MONITORING_ENVIRONMENT=production
      - MONITORING_CLUSTER=stone-prd-rh01
      - MONITORING_SAMPLE_RATE_ERRORS=0.2

patches:
  - path: add-service-certs-patch.yaml
    target:
      group: ""
      version: v1
      kind: Service
      name: proxy
  - path: oauth2-proxy-args-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: proxy
  - path: remove-run-as-user-proxy-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: proxy
  - path: set-replicas-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
  - path: set-redirect-uri.yaml
    target:
      name: dex-client
      kind: ServiceAccount
  - path: set-hostname.yaml
    target:
      kind: Route
      version: v1

namespace: konflux-ui
