apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  template:
    spec:
      containers:
        - name: crossplane
          resources:
            limits:
              memory: 4Gi
