apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

generators:
  - loki-helm-generator.yaml
  - grafana-helm-generator.yaml

# secretGenerator:
#   - name: kubearchive-loki
#     namespace: product-kubearchive-logging
#     literals:
#       - USERNAME=admin
#       - PASSWORD="$(openssl rand -base64 20)"
