---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - files:
      - ./config.yaml
    name: etcd-shield-config
# generatorOptions:
#   # until https://github.com/kubernetes-sigs/kustomize/issues/4475 is fixed
#   disableNameSuffixHash: true
images:
  - name: etcd-shield
    newName: quay.io/konflux-ci/etcd-shield
    newTag: 94885d051db284f214f43d76df2f9bd4c9fe993f
namespace: etcd-shield
resources:
  - deployment.yaml
  - ns.yaml
  - rbac.yaml
  - service.yaml
  - webhook.yaml
  - etcd_shield_alerts.yaml
  - ./metrics
