apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - https://github.com/redhat-appstudio/internal-infra-deployments/components/monitoring/blackbox-exporter/staging/private/stone-stage-p01?ref=74e5503d63afea28b962f5aa1f3bdf6809aede77

namespace: appstudio-monitoring
