apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-infra-deployments/components/monitoring/blackbox-exporter/staging/private/stone-stage-p01?ref=6e76b56c63b75f25f3b8ad94ae243251f3b7b275

namespace: appstudio-monitoring
