apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - https://github.com/redhat-appstudio/internal-infra-deployments/components/monitoring/blackbox-exporter/staging/private/stone-stage-p01?ref=dceea2cefc253cc71736994fd43a2a94dd75ca95

namespace: appstudio-monitoring
