apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kanary-o11y-cronjob-trigger
rules:
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kanary-o11y-cronjob-trigger
subjects:
  - kind: Group
    name: konflux-o11y
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kanary-o11y-cronjob-trigger
