apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/konflux-ci/konflux-ci/operator/config/default?ref=238f6f41302dabaa92615eb2c85255c877723d58
  - konflux.yaml

images:
  - name: localhost/konflux-operator
    newName: quay.io/konflux-ci/konflux-operator
    newTag: 238f6f41302dabaa92615eb2c85255c877723d58
