apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-infra-deployments/components/monitoring/blackbox-exporter/staging/public/stone-stg-rh01?ref=32a353b0b06a6cd97a4ac44cc406f17843c5b6ca

namespace: appstudio-monitoring
