apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: konflux-ci-certificate-secret-reader
  namespace: konflux-ui
rules:
- apiGroups:
  - ""
  resourceNames:
  - konflux-ci-certificate
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
