apiVersion: batch/v1
kind: CronJob
metadata:
  name: namespace-claim-cleaner
  namespace: crossplane-system
spec:
  schedule: "0 * * * *" # every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: namespace-claim-cleaner
              image: quay.io/konflux-ci/task-runner:v1@sha256:b9ef0479b57a494368a12a02886c650314c9ac7391c6228f21065865aab71c9e
              command:
                - /bin/bash
                - /scripts/namespace-claim-cleaner.sh
              volumeMounts:
                - name: script-volume
                  mountPath: /scripts
                  readOnly: true
              resources:
                requests:
                  cpu: 250m
                  memory: 125Mi
                limits:
                  cpu: 250m
                  memory: 125Mi
              securityContext:
                readOnlyRootFilesystem: true
                runAsNonRoot: true
          volumes:
            - name: script-volume
              configMap:
                name: namespace-claim-cleaner-configmap
          restartPolicy: Never
          serviceAccountName: namespace-claim-cleaner
