resources:
  - ../base
  - rbac
  - https://github.com/TominoFTW/o11y/config/exporters/monitoring/registry/base?ref=f59481194d821a27a7dee8a0c8fb6d57d404eb42

images:
  - name: quay.io/redhat-appstudio/o11y
    newName: quay.io/redhat-appstudio/o11y
    newTag: bdfd86f30f3c42bd2b88ae4b693d028c069e3b6c
