resources:
  - rbac
  - external-secrets
  - https://github.com/redhat-appstudio/o11y/config/exporters/monitoring/kaexporter/base?ref=7178afafdcf09c0ad70c3322fbe4c972c7901bc5

images:
  - name: quay.io/redhat-appstudio/o11y
    newName: quay.io/redhat-appstudio/o11y
    newTag: 7178afafdcf09c0ad70c3322fbe4c972c7901bc5
