resources:
  - rbac
  - external-secrets
  - configs
  - https://github.com/redhat-appstudio/o11y/config/exporters/monitoring/kaexporter/base?ref=05d2ca5b75e37f9675f0a0eb70649d847cdb8813

images:
  - name: quay.io/redhat-appstudio/o11y
    newName: quay.io/redhat-appstudio/o11y
    newTag: 05d2ca5b75e37f9675f0a0eb70649d847cdb8813

patches:
  - path: ./configs/kaexporter-deployment-patch.yaml
