resources:
  - rbac
  - external-secrets
  - https://github.com/redhat-appstudio/o11y/config/exporters/monitoring/kaexporter/base?ref=59edde5269d5713c4e00e989176728741c4c8772

images:
  - name: quay.io/redhat-appstudio/o11y
    newName: quay.io/redhat-appstudio/o11y
    newTag: 59edde5269d5713c4e00e989176728741c4c8772
