apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: konflux-rbac-
resources:
- generate-support-clusterrolebinding-cp.yaml
- kyverno-background-crb.yaml
- kyverno-admission-cluster-role.yaml
