apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '10'
  name: cluster-pipeline-queue
spec:
  flavorFungibility:
    whenCanBorrow: MayStopSearch
    whenCanPreempt: TryNextFlavor
  namespaceSelector: {}
  preemption:
    borrowWithinCohort:
      policy: Never
    reclaimWithinCohort: Never
    withinClusterQueue: Never
  queueingStrategy: BestEffortFIFO
  resourceGroups:
  - coveredResources:
    - tekton.dev/pipelineruns
    - konflux-ci-dev-token
    - cpu
    - memory
    - aws-ip
    - mintmaker
    - konflux-release
    flavors:
    - name: default-flavor
      resources:
      - name: tekton.dev/pipelineruns
        nominalQuota: '400'
      - name: konflux-ci-dev-token
        nominalQuota: '300'
      - name: cpu
        nominalQuota: 1k
      - name: memory
        nominalQuota: 500Ti
      - name: aws-ip
        nominalQuota: '250'
      - name: mintmaker
        nominalQuota: '150'
      - name: konflux-release
        nominalQuota: '100'
  - coveredResources:
    - linux-amd64
    - linux-arm64
    - linux-x86-64
    - local
    - localhost
    flavors:
    - name: platform-group-1
      resources:
      - name: linux-amd64
        nominalQuota: '250'
      - name: linux-arm64
        nominalQuota: '250'
      - name: linux-x86-64
        nominalQuota: 1k
      - name: local
        nominalQuota: 1k
      - name: localhost
        nominalQuota: 1k
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ResourceFlavor
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '10'
  name: default-flavor
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ResourceFlavor
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '10'
  name: platform-group-1
spec: {}
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ResourceFlavor
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '10'
  name: platform-group-2
spec: {}
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ResourceFlavor
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '10'
  name: platform-group-3
spec: {}
