apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tekton-kueue-controller
  annotations:
    argocd.argoproj.io/sync-wave: "11"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  endpoints:
  - path: /metrics
    interval: 15s
    port: https
    scheme: https
    bearerTokenSecret:
      name: "metrics-reader"
      key: token
    tlsConfig:
      serverName: tekton-kueue-controller-manager-metrics-service.tekton-kueue.svc.cluster.local
      insecureSkipVerify: false
      ca:
        secret:
          name: controller-manager-metrics-server-cert
          key: ca.crt
  selector:
    matchLabels:
      app.kubernetes.io/name: tekton-kueue
