apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dex
  - proxy
  - route-and-oauth.yaml
  - ../../base
  - external-secret.yaml

images:
  - name: quay.io/konflux-ci/konflux-ui
    newTag: 8950772735a45860fca0b2de48fd6dfe863929cf

  - name: quay.io/konflux-ci/oauth2-proxy
    newTag: 0cbda5dd47037cae269bf04242d5f9dfe4f6c8db

namespace: konflux-ui
