apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dex
  - proxy
  - route-and-oauth.yaml
  - ../../base
  - external-secret.yaml

images:
  - name: quay.io/konflux-ci/konflux-ui
    newTag: 0968b43dba01ddeeb0efcddad93893df9c7cc5e4

  - name: quay.io/konflux-ci/oauth2-proxy
    newTag: 14e99c427a9ff3c6a24e63b78551a8d300d934b6

namespace: konflux-ui
