apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dex
  - proxy
  - route-and-oauth.yaml
  - ../../base

images:
  - name: quay.io/konflux-ci/konflux-ui
    newTag: 90445f4847e2d1fbc92cf0f216b987e9e5433963

  - name: quay.io/konflux-ci/oauth2-proxy
    newTag: 0cbda5dd47037cae269bf04242d5f9dfe4f6c8db

namespace: konflux-ui
