{
 "title": "KubeArchive Status Hemartin",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Prometheus", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(source_cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "KA Status - hemartin",
   "type": "text",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 0 },
   "options": {
    "content": "See the [KubeArchive SLO dashboard](/d/beqtfn88x35kwd/kubearchive-slos)\n\n*This dashboard may show incorrect results due to changes\nrequired in the o11y side from Konflux. Don't trust what\nyou see here and go to the Grafana instance in each of the\ncluster*\n\nThis dashboard is meant to be used with one cluster\nat a time. Please select a single cluster from\nthe Cluster dropdown just above this text. Check\n[Eran's aggregator page](https://eisraeli.pages.redhat.com/rhtap-link/#konflux-clusters)\nfor links of all the clusters.\n\n"
   }
  },
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Number of tenants",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (source_cluster) (kube_namespace_labels{})",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "% usage of memory on the namespace",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (namespace:container_memory_usage_bytes:sum{namespace=\"product-kubearchive\"}) / sum by (source_cluster) (namespace_memory:kube_pod_container_resource_limits:sum{namespace=\"product-kubearchive\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Restarts in the last 24 hours",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (increase(kube_pod_container_status_restarts_total{namespace=\"product-kubearchive\",pod=~\"kubearchive-operator-.*\"}[24h]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Read", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Number of read responses during period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (increase(http_server_request_duration_count{http_route!~\"(/livez|/readyz)\", exported_job=\"kubearchive.api\"}[$__range]))",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "Average of read latency during period (non 500)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (source_cluster) (kubearchive:api:latency{http_route!~\"(/livez|/readyz)\", http_status_code!=\"500\"})",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "% of 500 read responses during period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (increase(http_server_request_duration_count{http_route!~\"(/livez|/readyz)\", exported_job=\"kubearchive.api\", http_status_code=\"500\"}[$__range])) / sum by (source_cluster) (increase(http_server_request_duration_count{http_route!~\"(/livez|/readyz)\", exported_job=\"kubearchive.api\"}[$__range]))",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "Number of 500 read responses during period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (increase(http_server_request_duration_count{http_route!~\"(/livez|/readyz)\", exported_job=\"kubearchive.api\", http_status_code=\"500\"}[$__range]))",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  { "title": "Write", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Queued resource updates",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (workqueue_depth{})",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "Received resource updates in the last 24 hours",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (increase(workqueue_adds{}[24h]))",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "Number of accepted resources during period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (increase(http_server_request_duration_count{http_route=\"/\", exported_job=\"kubearchive.sink\"}[$__range]))",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "Average of ingestion latency during period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (source_cluster) (kubearchive:sink:latency{http_route!~\"(/livez|/readyz)\"})",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  { "title": "General health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Konflux UP Metric",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "konflux_up{source_cluster=~\"$cluster\", service=~\"kubearchive-.*\"}",
     "legendFormat": "{{ source_cluster }} - {{ service }}"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (queue) (workqueue_depth{source_cluster=~\"$cluster\", queue!=\"\"})",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Konflux UP Metric",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "konflux_up{source_cluster=~\"$cluster\", service=~\"kubearchive-.*\"}",
     "legendFormat": "{{ source_cluster }} - {{ service }}"
    }
   ]
  },
  {
   "title": "Queue retries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "workqueue_retries{source_cluster=~\"$cluster\"}",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Read latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (http_status_code, source_cluster) (kubearchive:api:latency{source_cluster=~\"$cluster\", http_route!~\"(/livez|/readyz)\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read DB latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (kubearchive:api:db_latency{source_cluster=~\"$cluster\"})",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "Ingestion latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (http_status_code, source_cluster) (kubearchive:sink:latency{source_cluster=~\"$cluster\", http_route!~\"(/livez|/readyz)\"})",
     "legendFormat": "{{ source_cluster }} - {{ http_status_code }}"
    }
   ]
  },
  {
   "title": "Ingestion DB latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (source_cluster) (kubearchive:sink:db_latency{source_cluster=~\"$cluster\"})",
     "legendFormat": "{{ source_cluster }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memory_used{source_cluster=~\"$cluster\", exported_job=~\"kubearchive.*\"}",
     "legendFormat": "{{ source_cluster }} - {{ exported_job }}"
    },
    {
     "expr": "go_memory_limit{source_cluster=~\"$cluster\", exported_job=~\"kubearchive.*\"}",
     "legendFormat": "{{ source_cluster }} - {{ exported_job }} - limit"
    }
   ]
  },
  {
   "title": "Namespace Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(namespace_memory:kube_pod_container_resource_limits:sum{source_cluster=~\"$cluster\", namespace=\"product-kubearchive\"}[4h])",
     "legendFormat": "Memory Limits"
    },
    {
     "expr": "avg_over_time(namespace_memory:kube_pod_container_resource_requests:sum{source_cluster=~\"$cluster\", namespace=\"product-kubearchive\"}[4h])",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "namespace:container_memory_usage_bytes:sum{source_cluster=~\"$cluster\", namespace=\"product-kubearchive\"}",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "avg_over_time(namespace_cpu:kube_pod_container_resource_limits:sum{source_cluster=~\"$cluster\", namespace=\"product-kubearchive\"}[4h])",
     "legendFormat": "CPU Limits"
    },
    {
     "expr": "avg_over_time(namespace_cpu:kube_pod_container_resource_requests:sum{source_cluster=~\"$cluster\", namespace=\"product-kubearchive\"}[4h])",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "namespace:container_cpu_usage:sum{source_cluster=~\"$cluster\", namespace=\"product-kubearchive\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Operator Container Restarts per 15m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"product-kubearchive\", source_cluster=~\"$cluster\", pod=~\"kubearchive-operator-.*\"}[15m])",
     "legendFormat": "{{ source_cluster }} - {{ pod }}"
    }
   ]
  },
  {
   "title": "Cloud Events Increases 1 hour",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "panels": [
    {
     "title": "All CloudEvents - 1 hour increase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 242 },
     "targets": [
      {
       "expr": "sum by (queue) (increase(workqueue_adds{exported_job=\"kubearchive.operator\", source_cluster=~\"$cluster\"}[1h]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "No Conf CloudEvents - 1 hour increase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 242 },
     "targets": [
      {
       "expr": "sum by (resource_type) (increase(kubearchive_cloudevents_total{source_cluster=~\"$cluster\", result=\"no_conf\"}[1h]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Insert CloudEvents - 1 hour increase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 250 },
     "targets": [
      {
       "expr": "sum by (resource_type) (increase(kubearchive_cloudevents_total{source_cluster=~\"$cluster\", result=\"insert\"}[1h]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "No Match CloudEvents - 1 hour increase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 250 },
     "targets": [
      {
       "expr": "sum by (resource_type) (increase(kubearchive_cloudevents_total{source_cluster=~\"$cluster\", result=\"no_match\"}[1h]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Update CloudEvents - 1 hour increase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 258 },
     "targets": [
      {
       "expr": "sum by (resource_type) (increase(kubearchive_cloudevents_total{source_cluster=~\"$cluster\", result=\"update\"}[1h]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error CloudEvents - 1 hour increase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 258 },
     "targets": [
      {
       "expr": "sum by (resource_type) (increase(kubearchive_cloudevents_total{source_cluster=~\"$cluster\", result=\"error\"}[1h]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}