apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Ring 2 production rollout patches
# Add patches here when deploying to ring 2 clusters
# Clear this file (leave only these comments) after promoting to all rings

resources:
  - ../../base

patches:
  # Hold back on build 830 until Ring 2 promotion
  - target:
      kind: CatalogSource
      name: custom-operators
    patch: |-
      - op: replace
        path: /spec/image
        value: quay.io/openshift-pipeline/pipelines-index-4.18@sha256:a4aa211a70b0a92c98c885cca8fed2cce490e3fec656ad1ea68bf7e7c3c18304
  - target:
      kind: Subscription
      name: openshift-pipelines-operator
    patch: |-
      - op: add
        path: /spec/config/env/-
        value:
          name: IMAGE_PIPELINES_CONTROLLER
          value: "quay.io/openshift-pipeline/pipelines-resolvers-rhel9@sha256:7cd91bc4c0f3469ec4c39d08d818b00c90ce07456364910e49ad5e1430f3110a"
      - op: add
        path: /spec/config/env/-
        value:
          name: IMAGE_PAC_PAC_CONTROLLER
          value: "quay.io/openshift-pipeline/pipelines-pipelines-as-code-controller-rhel9@sha256:1b1e365cfdcc85646d5890232a04bad8c7ba9ebb0db36042eeda5961f8106567"
      - op: add
        path: /spec/config/env/-
        value:
          name: IMAGE_PAC_PAC_WEBHOOK
          value: "quay.io/openshift-pipeline/pipelines-pipelines-as-code-webhook-rhel9@sha256:0ccda15a17a405020fa199b3dce4a630e592da9dfdbd9778be1dcc9f4bdc3fbd"
      - op: add
        path: /spec/config/env/-
        value:
          name: IMAGE_PAC_PAC_WATCHER
          value: "quay.io/openshift-pipeline/pipelines-pipelines-as-code-watcher-rhel9@sha256:d100578068feb5482e2631b4fadc80b9687f129c7e303b55431ac41ce58f7758"
      - op: add
        path: /spec/config/env/-
        value:
          name: IMAGE_PAC_PAC_CLI
          value: "quay.io/openshift-pipeline/pipelines-pipelines-as-code-cli-rhel9@sha256:0fc0dd05236f14265e25cc770a7f9f3aeea2e27964a730dac39cf9f61d349bde"
