apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- https://github.com/flacatus/konflux-dummy-deploy//k8s?ref=af9b4550185300620210cf086dace680c81dc97c
images:
- name: quay.io/redhat-appstudio-qe/dummy-deployment
  newTag: af9b4550185300620210cf086dace680c81dc97c
patches:
- target:
    kind: ConfigMap
    name: dummy-deployment-config
  patch: |
    - op: replace
      path: /data/DISPLAY_TEXT
      value: "Hello from STAGE!"
