apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../development
  - artifact-registry-proxy
  - container-image-proxy
  - etcd-shield
  - konflux-operator
# - kueue # TODO: Uncomment this once e2e tests use solely the rd-dev overlay
  - kyverno
  - multi-platform-controller
  - policies
  - smee-client
  - repository-validator

patchesStrategicMerge:
  - delete-legacy-konflux-member-appsets.yaml

patches:
  - path: pipeline-service-operator-patch.yaml
    target:
      kind: ApplicationSet
      version: v1alpha1
      name: pipeline-service
