apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base-snapshot
images:
- name: ghcr.io/chmouel/gosmee
  digest: sha256:60b8db1f68cc4b72366fff941fb2db9a53c3b7a94f23a5e45bd10a777cf7be2f
- name: quay.io/konflux-ci/smee-sidecar
  digest: sha256:27da87ab41c0fab7d18f2af5596631c941d62506ae07fcbe95881b7f8d6d14f3
patches:
- path: patches/server-url-patch.yaml
  target:
    name: gosmee-client
    kind: Deployment
