apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    prometheusK8s:
      retentionSize: 10GB
      volumeClaimTemplate:
        spec:
          storageClassName: ibmc-vpc-block-metro-retain-10iops-tier
          resources:
            requests:
              storage: 100Gi
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        - key: "node-role.kubernetes.io/infra"
          effect: "NoSchedule"
          operator: "Exists"
    alertmanagerMain:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        - key: "node-role.kubernetes.io/infra"
          effect: "NoSchedule"
          operator: "Exists"
    thanosQuerier:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        - key: "node-role.kubernetes.io/infra"
          effect: "NoSchedule"
          operator: "Exists"
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        - key: "node-role.kubernetes.io/infra"
          effect: "NoSchedule"
          operator: "Exists"
