apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    prometheusK8s:
      retentionSize: 10GB
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        - key: "node-role.kubernetes.io/infra"
          effect: "NoSchedule"
          operator: "Exists"
    alertmanagerMain:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        - key: "node-role.kubernetes.io/infra"
          effect: "NoSchedule"
          operator: "Exists"
    thanosQuerier:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        - key: "node-role.kubernetes.io/infra"
          effect: "NoSchedule"
          operator: "Exists"
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        - key: "node-role.kubernetes.io/infra"
          effect: "NoSchedule"
          operator: "Exists"
