---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-cardinality-exporter
  labels:
    app: prometheus-cardinality-exporter
spec:
  endpoints:
    - port: http
      path: /metrics
      # Exporter runs every couple of hours. No need for frequent scraping.
      interval: 10m
  selector:
    matchLabels:
      app: prometheus-cardinality-exporter
