apiVersion: konflux.konflux-ci.dev/v1alpha1
kind: Konflux
metadata:
  name: konflux
spec:
  telemetry:
    enabled: true
    spec:
      segmentKeySecretRef:
        name: segment-write-key
        key: SEGMENT_WRITE_KEY
