apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multi-platform-controller

resources:
- common
- rbac
- https://github.com/konflux-ci/multi-platform-controller/deploy/operator?ref=c28c4a0108c120b23004430b0a475e5d7cfdf41a
- https://github.com/konflux-ci/multi-platform-controller/deploy/otp?ref=c28c4a0108c120b23004430b0a475e5d7cfdf41a

images:
- name: multi-platform-controller
  newName: quay.io/konflux-ci/multi-platform-controller
  newTag: c28c4a0108c120b23004430b0a475e5d7cfdf41a
- name: multi-platform-otp-server
  newName: quay.io/konflux-ci/multi-platform-controller-otp-service
  newTag: c28c4a0108c120b23004430b0a475e5d7cfdf41a
