apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multi-platform-controller

resources:
- common
- https://github.com/konflux-ci/multi-platform-controller/deploy/operator?ref=e2029306d11beb2b821442860ceaaa5d439d6c21
- https://github.com/konflux-ci/multi-platform-controller/deploy/otp?ref=e2029306d11beb2b821442860ceaaa5d439d6c21


images:
- name: multi-platform-controller
  newName: quay.io/konflux-ci/multi-platform-controller
  newTag: e2029306d11beb2b821442860ceaaa5d439d6c21
- name: multi-platform-otp-server
  newName: quay.io/konflux-ci/multi-platform-controller-otp-service
  newTag: e2029306d11beb2b821442860ceaaa5d439d6c21
