apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multi-platform-controller

resources:
- common
- rbac
- https://github.com/konflux-ci/multi-platform-controller/deploy/operator?ref=334b18f484ac4796122daf0636ff2f4b147866de
- https://github.com/konflux-ci/multi-platform-controller/deploy/otp?ref=334b18f484ac4796122daf0636ff2f4b147866de


images:
- name: multi-platform-controller
  newName: quay.io/konflux-ci/multi-platform-controller
  newTag: 334b18f484ac4796122daf0636ff2f4b147866de
- name: multi-platform-otp-server
  newName: quay.io/konflux-ci/multi-platform-controller-otp-service
  newTag: 334b18f484ac4796122daf0636ff2f4b147866de
