apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/redhat-appstudio/internal-infra-deployments/components/repository-validator/staging?ref=1c630da05130802d93022bd0b76dfa31d6ca66ae
configMapGenerator:
  - name: config
    literals:
      - config=*
generatorOptions:
  labels:
    app.kubernetes.io/name: repository-validator
namespace: repository-validator
