apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/staging
  - external-secrets/release-monitor-secret.yaml
  - https://github.com/konflux-ci/release-service/config/default?ref=617adbff10766dcab8d7773505c9c5847c48d42e
  - release_service_config.yaml
  - signing_configs.yaml

components:
  - ../k-components/manager-resources-patch

images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/konflux-ci/release-service
    newTag: 617adbff10766dcab8d7773505c9c5847c48d42e

namespace: release-service
