apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/staging
  - external-secrets/release-monitor-secret.yaml
  - https://github.com/konflux-ci/release-service/config/default?ref=98fbb94250e48bbcae6a135197c0f7f17e0a64bf
  - release_service_config.yaml
  - signing_configs.yaml

components:
  - ../k-components/manager-resources-patch

images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/konflux-ci/release-service
    newTag: 98fbb94250e48bbcae6a135197c0f7f17e0a64bf

namespace: release-service
