apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/staging
  - external-secrets/release-monitor-secret.yaml
  - https://github.com/konflux-ci/release-service/config/default?ref=3abc5019c03b3b1b52eb3742b4a29ecf00784e0f
  - release_service_config.yaml
  - signing_configs.yaml

components:
  - ../k-components/manager-resources-patch

images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/konflux-ci/release-service
    newTag: 3abc5019c03b3b1b52eb3742b4a29ecf00784e0f

namespace: release-service
