apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/image-controller/config/default?ref=452ad0720818a5bc6e7fbe05b5b3c784175fba0e

images:
- name: quay.io/konflux-ci/image-controller
  newName: quay.io/konflux-ci/image-controller
  newTag: 452ad0720818a5bc6e7fbe05b5b3c784175fba0e

namespace: image-controller

patches:
  - path: ./manager_resources_patch.yaml
  - path: ./pruner_cronjob_resources_patch.yaml
  - path: ./notification_resetter_cronjob_resources_patch.yaml
