apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/image-controller/config/default?ref=292f181e2ab5575c13f41ddf6aae446344f59783

images:
- name: quay.io/konflux-ci/image-controller
  newName: quay.io/konflux-ci/image-controller
  newTag: 292f181e2ab5575c13f41ddf6aae446344f59783

namespace: image-controller

patches:
  - path: ./manager_resources_patch.yaml
  - path: ./pruner_cronjob_resources_patch.yaml
