apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/image-controller/config/default?ref=ae94b530b287a9a648226d3e5583506822158e53

images:
- name: quay.io/konflux-ci/image-controller
  newName: quay.io/konflux-ci/image-controller
  newTag: ae94b530b287a9a648226d3e5583506822158e53

namespace: image-controller

patches:
  - path: ./manager_resources_patch.yaml
  - path: ./pruner_cronjob_resources_patch.yaml
