apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-results
resources:
  - db-ssl-cm.yaml
  - example-leader-election-cm.yaml
  - example-observability-cm.yaml
  - info-cm.yaml
  - logging-cm.yaml
  - retention-policy-cm.yaml
