apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base-snapshot

images:
  - name:  quay.io/konflux-ci/etcd-defrag
    newTag: 7a19f7b9b7bbdeb4f8d51e06d3319ac5c0555094fcbf2093d6e4d71f136afb55
