apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- path: ingress-ibm-cidrs.yaml
  target:
    group: networking.k8s.io
    kind: NetworkPolicy
    name: allow-webhook-ingress
    version: v1
- path: ingress-ibm-cidrs.yaml
  target:
    group: networking.k8s.io
    kind: NetworkPolicy
    name: allow-health-checks-ingress
    version: v1
