apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/
- ../policies/kubearchive/
- kueue/

patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: deny-unallowed-annotations
        namespace: tekton-kueue

