resources:
  - rbac
  - external-secrets
  - https://github.com/redhat-appstudio/o11y/config/exporters/monitoring/kaexporter/base?ref=cd48a7ad17234ef50526134e0ad628ce30894b5a

images:
  - name: quay.io/redhat-appstudio/o11y
    newName: quay.io/redhat-appstudio/o11y
    newTag: cd48a7ad17234ef50526134e0ad628ce30894b5a
