apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/konflux-ci/notification-service/config/default?ref=35ccbdd01f3e2f9c7a2e87c79a8c8a46519dfb21

images:
  - name: quay.io/konflux-ci/notification-service
    newName: quay.io/konflux-ci/notification-service
    newTag: 35ccbdd01f3e2f9c7a2e87c79a8c8a46519dfb21

namespace: notification-controller

patches:
  - path: topic_region_add.yaml
    target:
      name: notification-controller-controller-manager
      kind: Deployment
