apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/konflux-ci/notification-service/config/default?ref=6bb1addd78135976045ab35cfaea33147a7bad6d

images:
  - name: quay.io/konflux-ci/notification-service
    newName: quay.io/konflux-ci/notification-service
    newTag: 6bb1addd78135976045ab35cfaea33147a7bad6d

namespace: notification-controller

patches:
  - path: topic_region_add.yaml
    target:
      name: notification-controller-controller-manager
      kind: Deployment
