apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
  name: pipeline-service
  namespace: openshift-pipelines
spec:
  endpoints:
  - honorLabels: true
    interval: 15s
    path: /metrics
    port: metrics
    scheme: http
  jobLabel: app
  namespaceSelector:
    matchNames:
    - openshift-pipelines
  selector:
    matchLabels:
      app: pipeline-metrics-exporter
