apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: repository-validator
  labels:
    appstudio.redhat.com/deployment-clusters: tenant
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              selector:
                  matchExpressions:
                  - key: appstudio.redhat.com/select-none
                    operator: Exists
                  - key: appstudio.redhat.com/select-none
                    operator: DoesNotExist
              values:
                sourceRoot: components/repository-validator-rd
                ring: "empty-base"
                clusterDir: "empty-base"
          - list:
              elements: []

  template:
    metadata:
      name: repository-validator-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/rings/{{values.ring}}/{{values.clusterDir}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: repository-validator
        server: '{{server}}'
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 15s
