apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- catalog-source.yaml
- base-snapshot
- tekton-kueue

patches:
- path: subscription-source-patch.yaml
  target:
    group: operators.coreos.com
    kind: Subscription
    name: openshift-kueue-operator
