apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/production
  - https://github.com/konflux-ci/release-service/config/default?ref=b7a2c7b04cabc7ef43037f26e210c9542bdb8fc8
  - release_service_config.yaml
  - signing_configs.yaml

components:
  - ../k-components/manager-resources-patch

images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/konflux-ci/release-service
    newTag: b7a2c7b04cabc7ef43037f26e210c9542bdb8fc8

namespace: release-service
