apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/production
  - https://github.com/konflux-ci/release-service/config/default?ref=a971d3c8d10d07257d4afc70e342a09e85a3a33e
  - release_service_config.yaml
  - signing_configs.yaml

components:
  - ../k-components/manager-resources-patch

images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/konflux-ci/release-service
    newTag: a971d3c8d10d07257d4afc70e342a09e85a3a33e

namespace: release-service
