apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/production
  - https://github.com/konflux-ci/release-service/config/default?ref=d02b958bcf790f72dbb38625d5f851f843351f83
  - release_service_config.yaml
  - signing_configs.yaml

components:
  - ../k-components/manager-resources-patch

images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/konflux-ci/release-service
    newTag: d02b958bcf790f72dbb38625d5f851f843351f83

namespace: release-service
