apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dummy-deployment
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              selector:
                matchLabels:
                  appstudio.redhat.com/cluster-type: "tenant"
              values:
                sourceRoot: components/dummy-deployment-rd
                ring: "empty-base"
                clusterDir: "empty-base"
          - list:
              elements:
                - nameNormalized: stone-stage-p01
                  values.ring: ring-1
                  values.clusterDir: stone-stage-p01
                - nameNormalized: stone-stg-rh01
                  values.ring: ring-1
                  values.clusterDir: stone-stg-rh01
  template:
    metadata:
      name: dummy-deployment-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/rings/{{values.ring}}/{{values.clusterDir}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: konflux-dummy-deploy
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 15s
