apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/project-controller/config/default?ref=e0ecd1419264b4dff0814b1c87c2f8e754fc36b3

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: e0ecd1419264b4dff0814b1c87c2f8e754fc36b3

namespace: project-controller
