apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/project-controller/config/default?ref=bbc28a3bb12f8111190b8cc6fe094a68da3ecc89

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: bbc28a3bb12f8111190b8cc6fe094a68da3ecc89

namespace: project-controller
