apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/project-controller/config/default?ref=b8779103da76776ec2f9f877d3e374e6969b13a6

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: b8779103da76776ec2f9f877d3e374e6969b13a6

namespace: project-controller
