apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base-snapshot
- https://github.com/konflux-ci/kube-shard/operator/config/default?ref=91964cb3c5e65c071bfaf56f106b8750608cae6d
- konflux-tekton-shard-apishard.yaml

images:
- name: localhost/controller
  newName: quay.io/konflux-ci/kube-shard
  newTag: 91964cb3c5e65c071bfaf56f106b8750608cae6d
