apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base-snapshot
- https://github.com/konflux-ci/kube-shard/operator/config/default?ref=9e2da554f84da6ae593bbe66cbf3a5a4281bc8ec
- konflux-tekton-shard-apishard.yaml

images:
- name: localhost/controller
  newName: quay.io/konflux-ci/kube-shard
  newTag: 9e2da554f84da6ae593bbe66cbf3a5a4281bc8ec
