apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/pulp/pulp-access-controller/config/manifests?ref=f79e977b842e2be736723a5818aa9f3f4a459e4f

namespace: pulp-access-controller
