apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ka-kubearchive-credentials
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  dataFrom:
    - extract:
        key: stonesoup/staging/monitoring/exporters/kaexporter
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: ka-kubearchive-credentials
