apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- buildah-roks-seccomp-cp.yaml
- buildah-roks-scc.yaml
- buildah-roks-scc-clusterrole.yaml
- buildah-roks-scc-clusterrolebinding.yaml
