# MinIO Tenant root credentials. Same credentials are used in tekton-results-s3 for Tekton Results API.
apiVersion: v1
kind: Secret
metadata:
  name: minio-storage-configuration
  namespace: tekton-results
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
type: Opaque
stringData:
  config.env: |
    export MINIO_ROOT_USER=minioadmin
    export MINIO_ROOT_PASSWORD=minioadmin
