name: Forbid ClusterPolicies outside Policies component

on:
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/forbid-clusterpolicies.yaml
      - hack/forbid-clusterpolicies.sh
      - hack/kustomize-build-with-retry.sh
      - 'components/**'
      - '!components/policies/**'

jobs:
  forbid-clusterpolicies:
    name: Forbid ClusterPolicies outside Policies component
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Kustomize
        uses: multani/action-setup-kustomize@bf96e027caf74ab03bb3f79bac2addb331b28f1d
        with:
          version: 5.8.1

      - name: Run forbid-clusterpolicies script
        env:
          OUTPUT: GITHUB
        run: |
          find argo-cd-apps components -name 'kustomization.yaml' \
            ! -path '*/k-components/*' \
            ! -path '*konflux-operator/*/cr/*' \
            ! -path '*konflux-operator/rings/*/base/cr/*' \
            ! -path 'components/policies/*' \
            ! -path 'components/repository-validator/staging/*' \
            ! -path 'components/repository-validator/production/*' \
            ! -path 'components/monitoring/blackbox/staging/*' \
            ! -path 'components/monitoring/blackbox/production/*' \
            | \
            xargs -I {} -n1 -P8  bash -c './hack/forbid-clusterpolicies.sh $(dirname "{}")'
