name: Run Kyverno tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/kyverno-policies-tests.yaml'
      - 'components/kyverno/**'
      - 'components/policies/production/**'
      - 'components/policies-rd/**'

jobs:
  kyverno-test:
    name: Run Kyverno tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Install Kyverno CLI
        uses: kyverno/action-install-cli@fcee92fca5c883169ef9927acf543e0b5fc58289 # v0.2.0
        with:
          release: 'v1.13.4'

      - name: Run Kyverno Tests
        run: |
          kyverno test ./
