---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.konflux-ci.dev/aggregate-to-contributor: "true"
  name: konflux-contributor-pipelineruns.tekton.dev
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - get
      - list
      - watch
