apiVersion: konflux.konflux-ci.dev/v1alpha1
kind: Konflux
metadata:
  name: konflux
spec:
  imageController:
    enabled: true
    spec:
      imageControllerManager:
        replicas: 1
        manager:
          resources:
            requests:
              cpu: 500m
              memory: 6Gi
            limits:
              cpu: 500m
              memory: 6Gi
      imagePruner:
        resources:
          requests:
            cpu: 150m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi
      notificationResetter:
        resources:
          requests:
            cpu: 150m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 1Gi
