apiVersion: v1
kind: ConfigMap
metadata:
  name: vmalert-poc-rules
  labels:
    app.kubernetes.io/name: vmalert
    app.kubernetes.io/part-of: mimir-poc
data:
  pod-cpu.yaml: |
    groups:
    - name: vmalert-poc-recording-rules
      interval: 1m
      eval_delay: 2m
      rules:
      - record: konflux_poc:cluster_pod_cpu_usage_cores:sum_rate5m
        expr: sum by (source_cluster, source_environment, source_pipeline) (rate(container_cpu_usage_seconds_total{source_prometheus="platform",container!="",pod!=""}[5m]))
        labels:
          source_prometheus: vmalert
          recording_engine: vmalert-poc
