apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - konflux-externalpuller-bot-actions.yaml
  - konflux-integrationtest-bot-actions.yaml
  - konflux-model-bot-actions.yaml
  - konflux-secrets-bot-actions.yaml
  - konflux-tester-internalbot-actions.yaml
  - konflux-viewer-bot-actions.yaml
